using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class BravoDatabase : MonoBehaviour {
	public List<CSGOSkins> b = new List<CSGOSkins> ();

	void Start () {
		b.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 3.93f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 1.07f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 1.05f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 1.03f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 1.61f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 16.16f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Demeter"});
		b.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.52f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 3.59f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.94f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.97f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 1.82f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 28.99f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Shattered"});
		b.Add(new CSGOSkins() { prize = 0.42f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 2.70f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 1.07f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 0.95f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 1.05f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 2.58f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 13.52f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SG 553",secondname = "Wave Spray"});
		b.Add(new CSGOSkins() { prize = 0.53f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Bone Pile"});
		b.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Bone Pile"});
		b.Add(new CSGOSkins() { prize = 2.44f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Bone Pile"});
		b.Add(new CSGOSkins() { prize = 1.48f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Bone Pile"});
		b.Add(new CSGOSkins() { prize = 1.53f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Bone Pile"});
		b.Add(new CSGOSkins() { prize = 15.36f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Bone Pile"});
		b.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 0.58f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 3.21f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 1.05f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 1.13f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 1.66f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 23.23f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Black Limba"});
		b.Add(new CSGOSkins() { prize = 0.54f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Tempest"});
		b.Add(new CSGOSkins() { prize = 0.65f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Tempest"});
		b.Add(new CSGOSkins() { prize = 2.70f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Tempest"});
		b.Add(new CSGOSkins() { prize = 1.30f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Tempest"});
		b.Add(new CSGOSkins() { prize = 1.39f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Tempest"});
		b.Add(new CSGOSkins() { prize = 10.66f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Tempest"});
		b.Add(new CSGOSkins() { prize = 3.10f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 4.20f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 3.85f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 6.96f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 21.86f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 11.96f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 9.97f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 10.30f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 23.65f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 339.81f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Overgrowth"});
		b.Add(new CSGOSkins() { prize = 3.13f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 3.24f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 2.73f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 3.34f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 13.06f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 8.36f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 9.39f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 8.77f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 9.96f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 63.02f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Graven"});
		b.Add(new CSGOSkins() { prize = 3.43f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 3.06f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 3.39f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 8.57f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 11.09f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 11.82f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 12.47f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 77.33f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Zirka"});
		b.Add(new CSGOSkins() { prize = 3.17f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Bright Water"});
		b.Add(new CSGOSkins() { prize = 3.45f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Bright Water"});
		b.Add(new CSGOSkins() { prize = 10.2f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Bright Water"});
		b.Add(new CSGOSkins() { prize = 11.91f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Bright Water"});
		b.Add(new CSGOSkins() { prize = 28.44f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Graphite"});
		b.Add(new CSGOSkins() { prize = 28.94f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Graphite"});
		b.Add(new CSGOSkins() { prize = 104.65f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Graphite"});
		b.Add(new CSGOSkins() { prize = 137.53f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "Graphite"});
		b.Add(new CSGOSkins() { prize = 21.78f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Ocean Foam"});
		b.Add(new CSGOSkins() { prize = 23.29f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Ocean Foam"});
		b.Add(new CSGOSkins() { prize = 75.26f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Ocean Foam"});
		b.Add(new CSGOSkins() { prize = 92.16f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Ocean Foam"});
		b.Add(new CSGOSkins() { prize = 19.99f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 20.81f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 19.94f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 20.94f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 72.80f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 57.50f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 56.50f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 72.84f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 180.51f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Emerald Dragon"});
		b.Add(new CSGOSkins() { prize = 86.24f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 129.24f, type = "Red",condition ="Well-Worn",stattrak = "", firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 137.61f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 214.20f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 348.0f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 413.12f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 535.36f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 1260.0f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fire Serpent"});
		b.Add(new CSGOSkins() { prize = 8.98f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Golden Koi"});
		b.Add(new CSGOSkins() { prize = 9.27f, type = "Red",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Golden Koi"});
		b.Add(new CSGOSkins() { prize = 85.52f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Golden Koi"});
		b.Add(new CSGOSkins() { prize = 66.94f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Golden Koi"});
	
		b.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		b.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		b.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		b.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		b.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		b.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		b.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		b.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		b.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		b.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		b.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		b.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		b.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		b.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		b.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		b.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		b.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		b.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		b.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		b.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		b.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		b.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		b.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		b.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		b.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		b.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		b.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		b.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		b.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		b.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		b.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		b.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		b.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		b.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		b.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		b.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		b.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		b.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		b.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		b.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		b.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		b.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
	}
