using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class BreakoutDatabase : MonoBehaviour {
	public List<CSGOSkins> br = new List<CSGOSkins> ();

	void Start () {
	
		br.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.8f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MP7",secondname = "Urban Hazard"});
		br.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Negev",secondname = "Desert-Strike"});
		br.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 1.04f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.33f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 1.1f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 5.98f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Abyss"});
		br.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Labyrinth"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 1.1f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Ivory"});
		br.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Koi"});
		br.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Koi"});
		br.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Koi"});
		br.Add(new CSGOSkins() { prize = 0.72f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Koi"});
		br.Add(new CSGOSkins() { prize = 0.91f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Koi"});
		br.Add(new CSGOSkins() { prize = 1.98f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Koi"});
		br.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 1.8f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 0.95f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 1.3f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 2.29f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Supernova"});
		br.Add(new CSGOSkins() { prize = 0.3f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.72f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.7f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.97f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 2.08f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Osiris"});
		br.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.2f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.26f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.68f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.62f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.64f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 0.65f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 1.08f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 3.62f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tigris"});
		br.Add(new CSGOSkins() { prize = 1.62f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Conspiracy"});
		br.Add(new CSGOSkins() { prize = 1.69f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Conspiracy"});
		br.Add(new CSGOSkins() { prize = 2.13f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Conspiracy"});
		br.Add(new CSGOSkins() { prize = 6.77f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Conspiracy"});
		br.Add(new CSGOSkins() { prize = 7.05f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Conspiracy"});
		br.Add(new CSGOSkins() { prize = 11.3f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Conspiracy"});
		br.Add(new CSGOSkins() { prize = 0.93f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 1.06f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 0.93f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 1.33f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 2.08f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 2.35f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 2.55f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 2.76f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 4.49f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 11.0f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Fowl Play"});
		br.Add(new CSGOSkins() { prize = 1.98f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 2.86f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 2.26f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 3.2f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 4.93f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 5.99f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 9.75f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 9.09f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 14.2f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 22.6f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Water Elemental"});
		br.Add(new CSGOSkins() { prize = 5.84f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 7.1f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 6.29f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 8.4f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 10.75f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 18.4f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 19.6f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 19.3f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 35.5f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 48.4f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Cyrex"});
		br.Add(new CSGOSkins() { prize = 2.44f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 3.76f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 4.11f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 6.75f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 12.8f, type = "Red",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 6.7f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 9.1f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 11.4f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 24.1f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Asiimov"});
		br.Add(new CSGOSkins() { prize = 75.9f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Asiimov"});
	
		br.Add(new CSGOSkins() { prize = 102, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Butterfly Knife",secondname = "Blue Steel"});
		br.Add(new CSGOSkins() { prize = 144, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Blue Steel"});
		br.Add(new CSGOSkins() { prize = 72, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Butterfly Knife",secondname = "Boreal Forest"});
		br.Add(new CSGOSkins() { prize = 93, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Boreal Forest"});
		br.Add(new CSGOSkins() { prize = 108, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Butterfly Knife",secondname = "Crimson Web"});
		br.Add(new CSGOSkins() { prize = 182, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Crimson Web"});
		br.Add(new CSGOSkins() { prize = 231, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Butterfly Knife",secondname = "Fade"});
		br.Add(new CSGOSkins() { prize = 324, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Fade"});
		br.Add(new CSGOSkins() { prize = 71, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Butterfly Knife",secondname = "Forest DDPAT"});
		br.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Forest DDPAT"});
		br.Add(new CSGOSkins() { prize = 108, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Butterfly Knife",secondname = "Case Hardened"});
		br.Add(new CSGOSkins() { prize = 200, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Case Hardened"});
		br.Add(new CSGOSkins() { prize = 66, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Butterfly Knife",secondname = "Safari Mesh"});
		br.Add(new CSGOSkins() { prize = 79, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Safari Mesh"});
		br.Add(new CSGOSkins() { prize = 69, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Butterfly Knife",secondname = "Scorched"});
		br.Add(new CSGOSkins() { prize = 109, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Scorched"});
		br.Add(new CSGOSkins() { prize = 191, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Butterfly Knife",secondname = "Slaughter"});
		br.Add(new CSGOSkins() { prize = 380, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Slaughter"});
		br.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Butterfly Knife",secondname = "Stained"});
		br.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Stained"});
		br.Add(new CSGOSkins() { prize = 87, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Butterfly Knife",secondname = "Night"});
		br.Add(new CSGOSkins() { prize = 126, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Butterfly Knife",secondname = "Night"});
	
	}
}
