using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class CacheDatabase : MonoBehaviour {
	public List<CSGOSkins> ca = new List<CSGOSkins> ();

	void Start () {

		ca.Add(new CSGOSkins() { prize = 0.12f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.27f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.14f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.26f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.45f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.88f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 1.19f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.78f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 1.51f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 3.81f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "AUG",secondname = "Radiation Hazard"});
		ca.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.11f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.11f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.19f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.64f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.27f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.38f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.33f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.76f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 6.07f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Chemical Green"});
		ca.Add(new CSGOSkins() { prize = 0.15f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.12f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.19f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.21f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 1.06f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.29f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.34f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.77f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Negev",secondname = "Nuclear Waste"});
		ca.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.18f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.18f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.35f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.42f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 1.12f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.43f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 1.12f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 3.66f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "P250",secondname = "Contamination"});
		ca.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.11f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.23f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 1.01f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.59f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.69f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.59f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 2.68f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 15.20f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Hot Shot"});
		ca.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.19f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.11f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.18f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.56f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.45f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 1.06f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.49f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 1.09f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 2.97f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "SG 553",secondname = "Fallout Warning"});
		ca.Add(new CSGOSkins() { prize = 0.74f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 1.43f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 1.94f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 3.09f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 3.21f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 8.01f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 3.79f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 10.98f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 26.57f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Toxic"});
		ca.Add(new CSGOSkins() { prize = 0.88f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 1.00f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 1.00f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 1.85f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 3.55f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 3.88f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 5.12f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 6.62f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 12.63f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 49.01f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Glock 18",secondname = "Reactor"});
		ca.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 0.46f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 0.42f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 1.61f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 3.39f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 1.65f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 3.45f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 7.07f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "XM1014",secondname = "Bone Machine"});
		ca.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 2.28f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 0.90f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 1.91f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 1.36f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 3.80f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 9.17f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Nuclear Garden"});
		ca.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 0.53f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 0.96f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 1.01f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 1.26f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 1.68f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 4.87f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 20.18f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MP9",secondname = "Setting Sun"});
		ca.Add(new CSGOSkins() { prize = 1.00f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 1.71f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 1.94f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 4.49f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 9.61f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 3.79f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 6.49f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 6.14f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 20.55f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 269.50f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Cerberus"});
		ca.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 1.02f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 0.58f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 1.69f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 3.29f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 4.38f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 7.25f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 4.18f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 10.90f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "FAMAS",secondname = "Styx"});
		ca.Add(new CSGOSkins() { prize = 30.73f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "FAMAS",secondname = "Styx"});
			
	}
}
