using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class ChromaDatabase : MonoBehaviour {
	public List<CSGOSkins> c1 = new List<CSGOSkins> ();

	void Start () {
		c1.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.88f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.80f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 1.05f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Catacombs"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.88f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "M249",secondname = "System Lock"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "XM1014",secondname = "Quicksilver"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.39f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 1.7f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "MP9",secondname = "Deadly Poison"});
		c1.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Battle-Scared",stattrak = "", firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.59f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "SCAR-20",secondname = "Grotto"});
		c1.Add(new CSGOSkins() { prize = 0.32f, type = "Purple",condition ="Battle-Scared",stattrak = "", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.4f, type = "Purple",condition ="Well-Worn",stattrak = "", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.30f, type = "Purple",condition ="Field-Tested",stattrak = "",  firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Minimal Wear",stattrak = "", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Factory New",stattrak = "", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.98f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 1.30f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.9f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 1.26f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 1.94f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Malachite"});
		c1.Add(new CSGOSkins() { prize = 0.37f, type = "Purple",condition ="Battle-Scared",stattrak = "", firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.37f, type = "Purple",condition ="Well-Worn",stattrak = "", firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.30f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.37f, type = "Purple",condition ="Minimal Wear",stattrak = "", firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.45f, type = "Purple",condition ="Factory New",stattrak = "", firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 1.32f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.99f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.89f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 1.22f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 2.07f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Serenity"});
		c1.Add(new CSGOSkins() { prize = 0.56f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 0.36f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 0.3f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 0.34f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 0.56f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 3.16f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 1.04f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 0.99f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 1.34f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 2.10f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "Dual Berettas",secondname = "Urban Shock"});
		c1.Add(new CSGOSkins() { prize = 0.34f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 0.34f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 0.34f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 0.44f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 1.4f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 1.49f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 1.49f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 1.49f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 2.3f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 8.65f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Naga"});
		c1.Add(new CSGOSkins() { prize = 1.48f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 1.68f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 1.79f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 1.92f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 2.27f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 4.92f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 5.94f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 4.84f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 6.41f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 11.45f, type = "Pink",condition ="Factory New",stattrak = "StatTrak",firstname = "P250",secondname = "Muertos"});
		c1.Add(new CSGOSkins() { prize = 2.54f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 3.97f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 2.81f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 4.54f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 7.32f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 7.54f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 13.54f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 7.54f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 15.2f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 25.54f, type = "Pink",condition ="Factory New",stattrak = "StatTrak",firstname = "M4A4",secondname = "Dragon King"});
		c1.Add(new CSGOSkins() { prize = 1.94f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 2.1f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 1.94f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 2.23f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 4.58f, type = "Pink",condition ="Factory New",stattrak = "", firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 8.46f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 11.75f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 8.18f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 10.89f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 18.24f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Cartel"});
		c1.Add(new CSGOSkins() { prize = 1.16f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Chatterbox"});
		c1.Add(new CSGOSkins() { prize = 1.21f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Chatterbox"});
		c1.Add(new CSGOSkins() { prize = 8.54f, type = "Red",condition ="Field-Tested",stattrak = "",firstname = "Galil AR",secondname = "Chatterbox"});
		c1.Add(new CSGOSkins() { prize = 4.76f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Chatterbox"});
		c1.Add(new CSGOSkins() { prize = 10, type = "Red",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Chatterbox"});
		c1.Add(new CSGOSkins() { prize = 51.99f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Chatterbox"});
		c1.Add(new CSGOSkins() { prize = 7.79f, type = "Red",condition ="Field-Tested",stattrak = "",firstname = "AWP",secondname = "Man-o-war"});
		c1.Add(new CSGOSkins() { prize = 7.4f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Man-o-war"});
		c1.Add(new CSGOSkins() { prize = 23, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Man-o-war"});
		c1.Add(new CSGOSkins() { prize = 25.15f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "AWP",secondname = "Man-o-war"});
	
		c1.Add(new CSGOSkins() { prize = 227, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "M9 Bayonet",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 280, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "M9 Bayonet",secondname = "Rust Coat"});
		c1.Add(new CSGOSkins() { prize = 300, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Rust Coat"});
		c1.Add(new CSGOSkins() { prize = 263, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "M9 Bayonet",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 355, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 164, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Demascus Steel"});
		c1.Add(new CSGOSkins() { prize = 314, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Demascus Steel"});
		c1.Add(new CSGOSkins() { prize = 367, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 259, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 340, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Marble Fade"});
		c1.Add(new CSGOSkins() { prize = 551, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Marble Fade"});
		c1.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 651, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Demascus Steel"});
		c1.Add(new CSGOSkins() { prize = 69, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Demascus Steel"});
		c1.Add(new CSGOSkins() { prize = 58, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Gut Knife",secondname = "Rust Coat"});
		c1.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Rust Coat"});
		c1.Add(new CSGOSkins() { prize = 84, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 34, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Ultraviolet"});
		c1.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Ultraviolet"});
		c1.Add(new CSGOSkins() { prize = 47, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Demascus Steel"});
		c1.Add(new CSGOSkins() { prize = 104, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Demascus Steel"});
		c1.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		c1.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		c1.Add(new CSGOSkins() { prize = 196, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Flip Knife",secondname = "Marble Fade"});
		c1.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Marble Fade"});
		c1.Add(new CSGOSkins() { prize = 51, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Ultraviolet"});
		c1.Add(new CSGOSkins() { prize = 79, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Ultraviolet"});
		c1.Add(new CSGOSkins() { prize = 98, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Damascus Steel"});
		c1.Add(new CSGOSkins() { prize = 131, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Damascus Steel"});
		c1.Add(new CSGOSkins() { prize = 189, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 309, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Doppler"});
		c1.Add(new CSGOSkins() { prize = 70, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Rust Coat"});
		c1.Add(new CSGOSkins() { prize = 84, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Rust Coat"});
		c1.Add(new CSGOSkins() { prize = 194, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Tiger Tooth"});
		c1.Add(new CSGOSkins() { prize = 754, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Tiger Tooth"});
	
	
	
	
	
	}
	}
