using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Chroma2Database : MonoBehaviour {
	public List<CSGOSkins> c2 = new List<CSGOSkins> ();

	void Start () {

	c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Origami"});
	c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.42f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Origami"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Man-o-war"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Man-o-war"});
		c2.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Negev",secondname = "Man-o-war"});
		c2.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Negev",secondname = "Man-o-war"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.58f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.54f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 1.59f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "P250",secondname = "Valence"});
		c2.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 1.28f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.66f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.74f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.94f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "Desert Eagle",secondname = "Bronze Deco"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "", firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "MP7",secondname = "Armor Core"});
		c2.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Battle-Scared",stattrak = "", firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 1.89f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 1.89f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 1.93f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 2.05f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 3.28f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 9.05f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "AK-47",secondname = "Elite Build"});
		c2.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",  firstname = "UMP-45",secondname = "Grand Prix"});
		c2.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Grand Prix"});
		c2.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "", firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Well-Worn",stattrak = "", firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Minimal Wear",stattrak = "", firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.42f, type = "Purple",condition ="Factory New",stattrak = "", firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.49f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.84f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 1.74f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "CZ75-Auto",secondname = "Pole Position"});
		c2.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.74f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.53f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.49f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.97f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 4.08f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "MAG-7",secondname = "Heat"});
		c2.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 0.66f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 0.70f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 1, type = "Purple",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 3.92f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 3.37f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 3.27f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 5.02f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "AWP",secondname = "Worm God"});
		c2.Add(new CSGOSkins() { prize = 0.98f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 0.95f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 0.97f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 1.18f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 3.18f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 2.26f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 2.50f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 3.86f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 9.58f, type = "Pink",condition ="Factory New",stattrak = "StatTrak",firstname = "FAMAS",secondname = "Djinn"});
		c2.Add(new CSGOSkins() { prize = 0.89f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 0.99f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 0.88f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 3.05f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 2.24f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 10.32f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Eco"});
		c2.Add(new CSGOSkins() { prize = 0.88f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 0.98f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 1.06f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 6.95f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 2.12f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 3.29f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 4.06f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 18.91f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Five-Seven",secondname = "Monkey Business"});
		c2.Add(new CSGOSkins() { prize = 1.82f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 1.74f, type = "Red",condition ="Field-Tested",stattrak = "",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 2.50f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 4.95f, type = "Red",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 5.48f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 3.72f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 9.14f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 20.06f, type = "Red",condition ="Factory New",stattrak = "StatTrak",firstname = "MAC-10",secondname = "Neon Rider"});
		c2.Add(new CSGOSkins() { prize = 6.07f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 7.45f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 8.72f, type = "Red",condition ="Field-Tested",stattrak = "",firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 13.42f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 28.83f, type = "Red",condition ="Factory New",stattrak = "", firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 15.34f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 20.46f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 25.93f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 44.38f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M4A1-S",secondname = "Hyper Beast"});
		c2.Add(new CSGOSkins() { prize = 144, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Hyper Beast"});

		c2.Add(new CSGOSkins() { prize = 227, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "M9 Bayonet",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 280, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "M9 Bayonet",secondname = "Rust Coat"});
		c2.Add(new CSGOSkins() { prize = 300, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Rust Coat"});
		c2.Add(new CSGOSkins() { prize = 263, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "M9 Bayonet",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 355, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 164, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Demascus Steel"});
		c2.Add(new CSGOSkins() { prize = 314, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Demascus Steel"});
		c2.Add(new CSGOSkins() { prize = 367, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 259, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 340, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Marble Fade"});
		c2.Add(new CSGOSkins() { prize = 551, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Marble Fade"});
		c2.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 651, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Demascus Steel"});
		c2.Add(new CSGOSkins() { prize = 69, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Demascus Steel"});
		c2.Add(new CSGOSkins() { prize = 58, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Gut Knife",secondname = "Rust Coat"});
		c2.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Rust Coat"});
		c2.Add(new CSGOSkins() { prize = 84, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 34, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Ultraviolet"});
		c2.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Ultraviolet"});
		c2.Add(new CSGOSkins() { prize = 47, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Demascus Steel"});
		c2.Add(new CSGOSkins() { prize = 104, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Demascus Steel"});
		c2.Add(new CSGOSkins() { prize = 196, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Flip Knife",secondname = "Marble Fade"});
		c2.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Marble Fade"});
		c2.Add(new CSGOSkins() { prize = 51, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Ultraviolet"});
		c2.Add(new CSGOSkins() { prize = 79, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Ultraviolet"});
		c2.Add(new CSGOSkins() { prize = 98, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Damascus Steel"});
		c2.Add(new CSGOSkins() { prize = 131, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Damascus Steel"});
		c2.Add(new CSGOSkins() { prize = 189, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 309, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Doppler"});
		c2.Add(new CSGOSkins() { prize = 70, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Rust Coat"});
		c2.Add(new CSGOSkins() { prize = 194, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Tiger Tooth"});
		c2.Add(new CSGOSkins() { prize = 754, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Tiger Tooth"});

}
}