using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Chroma3Database : MonoBehaviour {
	public List<CSGOSkins> c3 = new List<CSGOSkins> ();

	void Start () {
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.42f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Ventilators"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "", firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "G3SG1",secondname = "Orange Crash"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.58f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.54f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 1.59f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "M249",secondname = "Spectre"});
		c3.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 1.28f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.66f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.74f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.94f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "MP9",secondname = "Bioleak"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "", firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "P2000",secondname = "Oceanic"});
		c3.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Battle-Scared",stattrak = "", firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 1.89f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 1.89f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 1.93f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 2.05f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 3.28f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 9.05f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "Sawed-Off",secondname = "Fubar"});
		c3.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Field-Tested",stattrak = "",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 1.89f, type = "Blue",condition ="Factory New",stattrak = "", firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 1.89f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 1.93f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 2.05f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 3.28f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 9.05f, type = "Blue",condition ="Factory New",stattrak = "StatTrak",firstname = "SG 553",secondname = "Atlas"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Battle-Scared",stattrak = "",  firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Well-Worn",stattrak = "",  firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",  firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Minimal Wear",stattrak = "",  firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Factory New",stattrak = "",  firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Red Astor"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "", firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Well-Worn",stattrak = "", firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Minimal Wear",stattrak = "", firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.42f, type = "Purple",condition ="Factory New",stattrak = "", firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.49f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.84f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 1.74f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "Galil AR",secondname = "Firefight"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.74f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.53f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.49f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.97f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 4.08f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "SSG 08",secondname = "Ghost Crusader"});
		c3.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 0.66f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 0.70f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 1, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 3.92f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 3.37f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 3.27f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 5.02f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "Tec-9",secondname = "Re Entry"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.74f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.53f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.49f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.97f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 4.08f, type = "Purple",condition ="Factory New",stattrak = "StatTrak",firstname = "XM1014",secondname = "Black Tie"});
		c3.Add(new CSGOSkins() { prize = 0.98f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 0.95f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 0.97f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 1.18f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 3.18f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 2.26f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 2.50f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 3.86f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 9.58f, type = "Pink",condition ="Factory New",stattrak = "StatTrak",firstname = "AUG",secondname = "Fleet Flock"});
		c3.Add(new CSGOSkins() { prize = 0.89f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 0.99f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 0.88f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 3.05f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 3.05f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 2.24f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 10.32f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 10.32f, type = "Pink",condition ="Factory New",stattrak = "StatTrak",firstname = "P250",secondname = "Asiimov"});
		c3.Add(new CSGOSkins() { prize = 0.88f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 0.98f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 1.06f, type = "Pink",condition ="Field-Tested",stattrak = "",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 6.95f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 6.95f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 2.12f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 3.29f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 4.06f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 18.91f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 18.91f, type = "Pink",condition ="Factory New",stattrak = "StatTrak",firstname = "UMP-45",secondname = "Primal Saber"});
		c3.Add(new CSGOSkins() { prize = 1.82f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 1.82f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 1.74f, type = "Red",condition ="Field-Tested",stattrak = "",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 2.50f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 4.95f, type = "Red",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 5.48f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 5.48f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 3.72f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 9.14f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 20.06f, type = "Red",condition ="Factory New",stattrak = "StatTrak",firstname = "PP-Bizon",secondname = "Judgement of Anubis"});
		c3.Add(new CSGOSkins() { prize = 6.07f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 7.45f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 8.72f, type = "Red",condition ="Field-Tested",stattrak = "",firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 13.42f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 28.83f, type = "Red",condition ="Factory New",stattrak = "", firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 15.34f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 20.46f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 25.93f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 44.38f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M4A1-S",secondname = "Chantincos Fire"});
		c3.Add(new CSGOSkins() { prize = 144, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Chantincos Fire"});

		c3.Add(new CSGOSkins() { prize = 227, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "M9 Bayonet",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 280, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "M9 Bayonet",secondname = "Rust Coat"});
		c3.Add(new CSGOSkins() { prize = 300, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Rust Coat"});
		c3.Add(new CSGOSkins() { prize = 263, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "M9 Bayonet",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 355, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 164, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Demascus Steel"});
		c3.Add(new CSGOSkins() { prize = 314, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Demascus Steel"});
		c3.Add(new CSGOSkins() { prize = 367, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 259, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 340, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Marble Fade"});
		c3.Add(new CSGOSkins() { prize = 551, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Marble Fade"});
		c3.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 651, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		c3.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		c3.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Demascus Steel"});
		c3.Add(new CSGOSkins() { prize = 69, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Demascus Steel"});
		c3.Add(new CSGOSkins() { prize = 58, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Gut Knife",secondname = "Rust Coat"});
		c3.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Rust Coat"});
		c3.Add(new CSGOSkins() { prize = 84, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 34, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Ultraviolet"});
		c3.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Ultraviolet"});
		c3.Add(new CSGOSkins() { prize = 47, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Demascus Steel"});
		c3.Add(new CSGOSkins() { prize = 104, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Demascus Steel"});
		c3.Add(new CSGOSkins() { prize = 196, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Flip Knife",secondname = "Marble Fade"});
		c3.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Marble Fade"});
		c3.Add(new CSGOSkins() { prize = 51, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Ultraviolet"});
		c3.Add(new CSGOSkins() { prize = 79, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Ultraviolet"});
		c3.Add(new CSGOSkins() { prize = 98, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Damascus Steel"});
		c3.Add(new CSGOSkins() { prize = 131, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Damascus Steel"});
		c3.Add(new CSGOSkins() { prize = 189, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 309, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Doppler"});
		c3.Add(new CSGOSkins() { prize = 70, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Rust Coat"});
		c3.Add(new CSGOSkins() { prize = 84, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Rust Coat"});
		c3.Add(new CSGOSkins() { prize = 194, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Tiger Tooth"});
		c3.Add(new CSGOSkins() { prize = 754, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Tiger Tooth"});




	}
	}
