using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class CobblestoneDatabase : MonoBehaviour {
	public List<CSGOSkins> co = new List<CSGOSkins> ();

	void Start () {
		co.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.08f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.10f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.46f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.25f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.25f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.36f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 3.00f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "P90",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.08f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.08f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.10f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 1.06f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.29f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.91f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.49f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 1.53f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 10.44f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.10f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.52f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.35f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.71f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 4.56f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Indigo"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.10f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.38f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.16f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 1.49f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Storm"});
		co.Add(new CSGOSkins() { prize = 0.09f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Briar"});
		co.Add(new CSGOSkins() { prize = 0.10f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Briar"});
		co.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Briar"});
		co.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Dual Berettas",secondname = "Briar"});
		co.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Dual Berettas",secondname = "Briar"});
		co.Add(new CSGOSkins() { prize = 0.35f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "Dual Berettas",secondname = "Briar"});
		co.Add(new CSGOSkins() { prize = 0.38f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 0.70f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 0.49f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 1.81f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 12.49f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 3.36f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 4.81f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 4.03f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 14.02f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 203.82f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "USP-S",secondname = "Royal Blue"});
		co.Add(new CSGOSkins() { prize = 0.32f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Green Apple"});
		co.Add(new CSGOSkins() { prize = 0.29f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Green Apple"});
		co.Add(new CSGOSkins() { prize = 0.31f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Green Apple"});
		co.Add(new CSGOSkins() { prize = 0.37f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Nova",secondname = "Green Apple"});
		co.Add(new CSGOSkins() { prize = 0.39f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Nova",secondname = "Green Apple"});
		co.Add(new CSGOSkins() { prize = 0.98f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Nova",secondname = "Green Apple"});
		co.Add(new CSGOSkins() { prize = 0.34f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Silver"});
		co.Add(new CSGOSkins() { prize = 0.34f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Silver"});
		co.Add(new CSGOSkins() { prize = 2.03f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Silver"});
		co.Add(new CSGOSkins() { prize = 0.76f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Silver"});
		co.Add(new CSGOSkins() { prize = 0.31f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.32f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.29f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.32f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.32f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.49f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.50f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.26f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 0.33f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 1.19f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Rust Coat"});
		co.Add(new CSGOSkins() { prize = 3.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Dark Age"});
		co.Add(new CSGOSkins() { prize = 2.91f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Dark Age"});
		co.Add(new CSGOSkins() { prize = 2.87f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Dark Age"});
		co.Add(new CSGOSkins() { prize = 2.07f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MP9",secondname = "Dark Age"});
		co.Add(new CSGOSkins() { prize = 1.99f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP9",secondname = "Dark Age"});
		co.Add(new CSGOSkins() { prize = 2.28f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MP9",secondname = "Dark Age"});
		co.Add(new CSGOSkins() { prize = 3.37f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Chainmail"});
		co.Add(new CSGOSkins() { prize = 3.27f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Chainmail"});
		co.Add(new CSGOSkins() { prize = 3.08f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Chainmail"});
		co.Add(new CSGOSkins() { prize = 2.02f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P2000",secondname = "Chainmail"});
		co.Add(new CSGOSkins() { prize = 2.39f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P2000",secondname = "Chainmail"});
		co.Add(new CSGOSkins() { prize = 3.19f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "P2000",secondname = "Chainmail"});
		co.Add(new CSGOSkins() { prize = 21.82f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 23.72f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 22.35f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 24.46f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 26.88f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 44.98f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 52.72f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 27.83f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 52.55f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 238.00f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Hand Cannon"});
		co.Add(new CSGOSkins() { prize = 25.62f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Chalice"});
		co.Add(new CSGOSkins() { prize = 23.82f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Chalice"});
		co.Add(new CSGOSkins() { prize = 27.23f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Chalice"});
		co.Add(new CSGOSkins() { prize = 19.37f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Chalice"});
		co.Add(new CSGOSkins() { prize = 217.92f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Knight"});
		co.Add(new CSGOSkins() { prize = 222.97f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Knight"});
		co.Add(new CSGOSkins() { prize = 700.52f, type = "Pink",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Knight"});
		co.Add(new CSGOSkins() { prize = 900.21f, type = "Pink",condition ="Factory New",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Knight"});
		co.Add(new CSGOSkins() { prize = 429.00f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 489.00f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 600.00f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 892.00f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 1170.00f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 1500.00f, type = "Red",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 2500.00f, type = "Red",condition ="Well-Worn",stattrak = "Souvenir", firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 5000.00f, type = "Red",condition ="Field-Tested",stattrak = "Souvenir", firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 10000.00f, type = "Red",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "AWP",secondname = "Dragon Lore"});
		co.Add(new CSGOSkins() { prize = 15000.00f, type = "Red",condition ="Factory New",stattrak = "Souvenir", firstname = "AWP",secondname = "Dragon Lore"});
	}
	}
