using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Dust2Database : MonoBehaviour {
	public List<CSGOSkins> d2 = new List<CSGOSkins> ();

	void Start () {
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.17f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.27f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 5.39f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Desert Storm"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.58f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.43f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.31f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 1.08f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 16.50f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "P250",secondname = "Sand Dune"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.09f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.39f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.14f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.32f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 3.16f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "SCAR-20",secondname = "Sand Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.24f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.27f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.33f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 3.21f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "P90",secondname = "Sand Spray"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.31f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 3.20f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "MP9",secondname = "Sand Dashed"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.02f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.24f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.14f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.25f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 3.21f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "Nova",secondname = "Predator"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.12f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.27f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.32f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.15f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.36f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 4.63f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Snake Camo"});
		d2.Add(new CSGOSkins() { prize = 0.10f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.14f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.09f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.21f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 1.69f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 4.37f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 4.50f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 4.58f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 9.42f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 114.16f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "AK-47",secondname = "Safari Mesh"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.07f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.33f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.67f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.88f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.74f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 2.49f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 149.92f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Orange Peel"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.21f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.32f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.46f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.28f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.68f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 33.83f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Palm"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.04f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.06f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 1.43f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 2.27f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 1.02f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 1.59f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 3.08f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Tec-9",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.07f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 1.31f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 1.48f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 1.33f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 2.47f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 21.10f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "SG 553",secondname = "Damascus Steel"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 1.06f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 1.72f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 1.71f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 3.13f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 28.28f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Brass"});
		d2.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 12.66f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 14.98f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 10.30f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 9.23f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 18.89f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "VariCamo"});
		d2.Add(new CSGOSkins() { prize = 0.26f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 0.22f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 0.44f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 23.54f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 4.44f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 10.15f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P2000",secondname = "Amber Fade"});
		d2.Add(new CSGOSkins() { prize = 18.05f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "P2000",secondname = "Amber Fade"});

	}
	}
