using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class eSportsWinterDatabase : MonoBehaviour {
	public List<CSGOSkins> e2 = new List<CSGOSkins> ();

	void Start () {

		e2.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 0.96f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.65f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.82f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Water Sigil"});
		e2.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 1.14f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Ghost Camo"});
		e2.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Azure Zebra"});
		e2.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Azure Zebra"});
		e2.Add(new CSGOSkins() { prize = 0.20f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Azure Zebra"});
		e2.Add(new CSGOSkins() { prize = 0.62f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Azure Zebra"});
		e2.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Azure Zebra"});
		e2.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Azure Zebra"});
		e2.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Steel Disruption"});
		e2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Steel Disruption"});
		e2.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Steel Disruption"});
		e2.Add(new CSGOSkins() { prize = 0.73f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Steel Disruption"});
		e2.Add(new CSGOSkins() { prize = 0.80f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Steel Disruption"});
		e2.Add(new CSGOSkins() { prize = 0.90f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Steel Disruption"});
		e2.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.73f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.59f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 0.79f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 1.30f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Nightshade"});
		e2.Add(new CSGOSkins() { prize = 3.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 1.73f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 1.93f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 2.38f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 13.33f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 8.29f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 7.91f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 12.35f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Blue Titanium"});
		e2.Add(new CSGOSkins() { prize = 0.62f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 0.68f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 0.63f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 0.66f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 0.80f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 2.12f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 2.20f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 1.76f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 2.01f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 2.56f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Blind Spot"});
		e2.Add(new CSGOSkins() { prize = 5.21f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Cobalt Disruption"});
		e2.Add(new CSGOSkins() { prize = 4.04f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Cobalt Disruption"});
		e2.Add(new CSGOSkins() { prize = 4.71f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Cobalt Disruption"});
		e2.Add(new CSGOSkins() { prize = 13.60f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Cobalt Disruption"});
		e2.Add(new CSGOSkins() { prize = 16.89f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Cobalt Disruption"});
		e2.Add(new CSGOSkins() { prize = 25.56f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Cobalt Disruption"});
		e2.Add(new CSGOSkins() { prize = 8.31f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 7.19f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 9.14f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 10.03f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 30.82f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 22.73f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 29.60f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 48.62f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "Electric Hive"});
		e2.Add(new CSGOSkins() { prize = 3.32f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 1.35f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 1.70f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 2.69f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 10.73f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 3.86f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 5.40f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 9.90f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Afterimage"});
		e2.Add(new CSGOSkins() { prize = 3.38f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "X-Ray"});
		e2.Add(new CSGOSkins() { prize = 4.21f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "X-Ray"});
		e2.Add(new CSGOSkins() { prize = 5.08f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "X-Ray"});
		e2.Add(new CSGOSkins() { prize = 16.48f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "X-Ray"});
		e2.Add(new CSGOSkins() { prize = 24.42f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "X-Ray"});
		e2.Add(new CSGOSkins() { prize = 36.80f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "X-Ray"});

		e2.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		e2.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		e2.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		e2.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		e2.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		e2.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		e2.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		e2.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		e2.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		e2.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		e2.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		e2.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		e2.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		e2.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		e2.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		e2.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		e2.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		e2.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		e2.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		e2.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		e2.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		e2.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		e2.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		e2.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		e2.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		e2.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		e2.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		e2.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		e2.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		e2.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		e2.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		e2.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		e2.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		e2.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		e2.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		e2.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		e2.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		e2.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		e2.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		e2.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		e2.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		e2.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});
	}
}
