using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class eSports2013Database : MonoBehaviour {
	public List<CSGOSkins> e1 = new List<CSGOSkins> ();

	void Start () {
		e1.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Memento"});
		e1.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Memento"});
		e1.Add(new CSGOSkins() { prize = 1.16f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Memento"});
		e1.Add(new CSGOSkins() { prize = 0.90f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Memento"});
		e1.Add(new CSGOSkins() { prize = 1.46f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Memento"});
		e1.Add(new CSGOSkins() { prize = 4.08f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Memento"});
		e1.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Doomkitty"});
		e1.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Doomkitty"});
		e1.Add(new CSGOSkins() { prize = 0.95f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Doomkitty"});
		e1.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Doomkitty"});
		e1.Add(new CSGOSkins() { prize = 0.83f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 0.73f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 0.62f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 3.23f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 2.66f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 2.61f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 2.45f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 3.25f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 20.35f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Faded Zebra"});
		e1.Add(new CSGOSkins() { prize = 1.80f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 2.19f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 1.97f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 2.21f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 11.82f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 3.09f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 4.31f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 3.90f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 5.72f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 90.43f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 2.84f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Splash"});
		e1.Add(new CSGOSkins() { prize = 2.57f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Splash"});
		e1.Add(new CSGOSkins() { prize = 9.74f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Splash"});
		e1.Add(new CSGOSkins() { prize = 7.95f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 7.37f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 24.19f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 1.58f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 2.03f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 1.70f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 2.12f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 10.31f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 3.53f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 3.63f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 4.25f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 4.90f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 97.18f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Orange DDPAT"});
		e1.Add(new CSGOSkins() { prize = 12.45f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "BOOM"});
		e1.Add(new CSGOSkins() { prize = 16.45f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "BOOM"});
		e1.Add(new CSGOSkins() { prize = 61.52f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "BOOM"});
		e1.Add(new CSGOSkins() { prize = 38.33f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "BOOM"});
		e1.Add(new CSGOSkins() { prize = 51.69f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "BOOM"});
		e1.Add(new CSGOSkins() { prize = 306.59f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "BOOM"});
		e1.Add(new CSGOSkins() { prize = 5.46f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 5.93f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 4.78f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 7.93f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 94.60f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 22.26f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 26.20f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 27.12f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 43.32f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 348.42f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Red Laminate"});
		e1.Add(new CSGOSkins() { prize = 14.24f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Death by Kitty"});
		e1.Add(new CSGOSkins() { prize = 23.98f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Death by Kitty"});
		e1.Add(new CSGOSkins() { prize = 68.34f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Death by Kitty"});
		e1.Add (new CSGOSkins () {prize = 104.79f,type = "Red",condition = "Minimal Wear",stattrak = "StatTrak",firstname = "P90",secondname = "Death by Kitty"});
		e1.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		e1.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		e1.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		e1.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		e1.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		e1.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		e1.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		e1.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		e1.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		e1.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		e1.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		e1.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		e1.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		e1.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		e1.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		e1.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		e1.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		e1.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		e1.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		e1.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		e1.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		e1.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		e1.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		e1.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		e1.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		e1.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		e1.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		e1.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		e1.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		e1.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		e1.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		e1.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		e1.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		e1.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		e1.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		e1.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		e1.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		e1.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		e1.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		e1.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		e1.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		e1.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
}

