using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class eSportsSummerDatabase : MonoBehaviour {
	public List<CSGOSkins> e3 = new List<CSGOSkins> ();

	void Start () {
	
		e3.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "XM1014",secondname = "Red Python"});
		e3.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.20f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 1.25f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.92f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 4.94f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Negev",secondname = "Bratatat"});
		e3.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.57f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.30f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.69f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 4.57f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Hexane"});
		e3.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Blood Tiger"});
		e3.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Blood Tiger"});
		e3.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Blood Tiger"});
		e3.Add(new CSGOSkins() { prize = 1.53f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Blood Tiger"});
		e3.Add(new CSGOSkins() { prize = 1.73f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Blood Tiger"});
		e3.Add(new CSGOSkins() { prize = 4.10f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Blood Tiger"});
		e3.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 1.73f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.30f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.75f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 8.54f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Ultraviolet"});
		e3.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Dark Water"});
		e3.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Dark Water"});
		e3.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dark Water"});
		e3.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dark Water"});
		e3.Add(new CSGOSkins() { prize = 0.85f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 1.58f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 0.83f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 3.27f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 18.0f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 2.42f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 4.24f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 3.46f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 16.87f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 320.0f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 0.62f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Steel Distuption"});
		e3.Add(new CSGOSkins() { prize = 0.58f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Steel Distuption"});
		e3.Add(new CSGOSkins() { prize = 0.76f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Steel Distuption"});
		e3.Add(new CSGOSkins() { prize = 2.12f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Steel Distuption"});
		e3.Add(new CSGOSkins() { prize = 2.08f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Steel Distuption"});
		e3.Add(new CSGOSkins() { prize = 3.60f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Steel Distuption"});
		e3.Add(new CSGOSkins() { prize = 1.36f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Ocean Foam"});
		e3.Add(new CSGOSkins() { prize = 0.91f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Ocean Foam"});
		e3.Add(new CSGOSkins() { prize = 3.68f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP7",secondname = "Ocean Foam"});
		e3.Add(new CSGOSkins() { prize = 2.95f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MP7",secondname = "Ocean Foam"});
		e3.Add(new CSGOSkins() { prize = 0.53f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.45f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.32f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.64f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 3.43f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.82f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.84f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.95f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 1.63f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 23.21f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Blue Streak"});
		e3.Add(new CSGOSkins() { prize = 0.98f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 2.35f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 1.00f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 1.03f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 0.82f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 1.49f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 12.9f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Virus"});
		e3.Add(new CSGOSkins() { prize = 1.45f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 1.27f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 2.69f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 4.25f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 5.46f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 14.51f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 3.89f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 4.49f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 8.14f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 12.61f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 15.09f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 30.33f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "Corticera"});
		e3.Add(new CSGOSkins() { prize = 1.17f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 1.47f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 1.35f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 1.82f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 13.01f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 3.56f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 5.72f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 3.42f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 5.88f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 42.14f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Bloomstick"});
		e3.Add(new CSGOSkins() { prize = 1.66f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 1.16f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 1.19f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 1.96f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 11.0f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 4.29f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 3.99f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 4.41f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 8.95f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 69.09f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AUG",secondname = "Bengal Tiger"});
		e3.Add(new CSGOSkins() { prize = 6.06f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 4.94f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 4.32f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 5.15f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 11.96f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 48.65f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 13.52f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 14.88f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 27.03f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 52.80f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Bullet Rain"});
		e3.Add(new CSGOSkins() { prize = 6.94f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 7.75f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 8.54f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 11.66f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 29.08f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 24.56f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 28.66f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 37.66f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 54.59f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Jaguar"});
		e3.Add(new CSGOSkins() { prize = 232.20f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Jaguar"});

		e3.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		e3.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		e3.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		e3.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		e3.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		e3.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		e3.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		e3.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		e3.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		e3.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		e3.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		e3.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		e3.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		e3.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		e3.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		e3.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		e3.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		e3.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		e3.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		e3.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		e3.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		e3.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		e3.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		e3.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		e3.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		e3.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		e3.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		e3.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		e3.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		e3.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		e3.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		e3.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		e3.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		e3.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		e3.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		e3.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		e3.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		e3.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		e3.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});
	
	}
	}
