using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class FalchionDatabase : MonoBehaviour {
	public List<CSGOSkins> f = new List<CSGOSkins> ();

	void Start () {

		f.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 0.46f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 0.69f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 1.78f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 1.73f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 1.33f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 2.08f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 2.53f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Torque"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 1.3f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Riot"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.52f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.82f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 4.35f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Elite Build"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Ranger"});
		f.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 1.27f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.98f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 2.53f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Bunsen Burner"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.76f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.57f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 3.14f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Rocket Pop"});
		f.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.2f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 1.06f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.64f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.69f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.75f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 1.81f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 5.93f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Handgun"});
		f.Add(new CSGOSkins() { prize = 0.23f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 0.2f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 1.33f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 0.54f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 16.87f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Negev",secondname = "Loudmouth"});
		f.Add(new CSGOSkins() { prize = 0.24f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.2f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.26f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.44f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.94f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.99f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.67f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 1.26f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 2.58f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MP9",secondname = "Ruby Poison Dart"});
		f.Add(new CSGOSkins() { prize = 0.96f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 1.23f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 0.96f, type = "Purple",condition ="Field-Tested",stattrak = "",firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 1.24f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 2.01f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 3.98f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 3.57f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 3.82f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 5.75f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 8.78f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Evil Daimyo"});
		f.Add(new CSGOSkins() { prize = 0.24f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.21f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.26f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.63f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.79f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 0.62f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 1.09f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 2.29f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Neural Net"});
		f.Add(new CSGOSkins() { prize = 1.48f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 1.38f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 1.51f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 2.38f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 5.38f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 4.61f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 3.87f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 5.29f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 9.74f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 25.2f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "SG 553",secondname = "Cyrex"});
		f.Add(new CSGOSkins() { prize = 2.02f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Nemesis"});
		f.Add(new CSGOSkins() { prize = 2.34f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Nemesis"});
		f.Add(new CSGOSkins() { prize = 3.68f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Nemesis"});
		f.Add(new CSGOSkins() { prize = 6.73f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP7",secondname = "Nemesis"});
		f.Add(new CSGOSkins() { prize = 9.42f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP7",secondname = "Nemesis"});
		f.Add(new CSGOSkins() { prize = 15.18f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "MP7",secondname = "Nemesis"});
		f.Add(new CSGOSkins() { prize = 1.61f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 1.57f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 1.65f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 2.23f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 3.47f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 4.56f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 3.63f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 4.97f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 6.72f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 18.1f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Yellow Jacket"});
		f.Add(new CSGOSkins() { prize = 8.76f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 14.17f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 17.89f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 25.76f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 36.48f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 25.76f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 31.73f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 47.56f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 79.06f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 191.41f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "Hyper Beast"});
		f.Add(new CSGOSkins() { prize = 8.07f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 9.45f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 12.1f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 16.77f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 26.1f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 27.7f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 32.47f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 39.04f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 52.56f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Aquamarine Revenge"});
		f.Add(new CSGOSkins() { prize = 120.56f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Aquamarine Revenge"});
	
		f.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Falchion",secondname = "Blue Steel"});
		f.Add(new CSGOSkins() { prize = 177, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Falchion",secondname = "Blue Steel"});
		f.Add(new CSGOSkins() { prize = 30, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Falchion",secondname = "Boreal Forest"});
		f.Add(new CSGOSkins() { prize = 53, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Falchion",secondname = "Boreal Forest"});
		f.Add(new CSGOSkins() { prize = 54, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Falchion",secondname = "Case Hardened"});
		f.Add(new CSGOSkins() { prize = 139, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Falchion",secondname = "Case Hardened"});
		f.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Falchion",secondname = "Crimson Web"});
		f.Add(new CSGOSkins() { prize = 162, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Falchion",secondname = "Crimson Web"});
		f.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Falchion",secondname = "Fade"});
		f.Add(new CSGOSkins() { prize = 116, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Falchion",secondname = "Fade"});
		f.Add(new CSGOSkins() { prize = 30, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Falchion",secondname = "Forest DDPAT"});
		f.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Falchion",secondname = "Forest DDPAT"});
		f.Add(new CSGOSkins() { prize = 104, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Falchion",secondname = "Safari Mesh"});
		f.Add(new CSGOSkins() { prize = 44, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Falchion",secondname = "Safari Mesh"});
		f.Add(new CSGOSkins() { prize = 70, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Falchion",secondname = "Scorched"});
		f.Add(new CSGOSkins() { prize = 67, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Falchion",secondname = "Scorched"});
		f.Add(new CSGOSkins() { prize = 84, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Falchion",secondname = "Slaughter"});
		f.Add(new CSGOSkins() { prize = 103, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Falchion",secondname = "Slaughter"});
	}
}
