using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Gamma2Database : MonoBehaviour {
	public List<CSGOSkins> g2 = new List<CSGOSkins> ();

	void Start () {
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 2.42f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Imprint"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.52f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.53f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.69f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 2.78f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Scumbria"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 1.04f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Ventilator"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 4.3f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Negev",secondname = "Dazzle"});
		g2.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 0.52f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 0.61f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 1.33f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 1.04f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 1.76f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 1.06f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 2.27f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 5.75f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Grim"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.89f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.33f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.61f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 1.38f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 6.25f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Briefing"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 1.1f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "XM1014",secondname = "Slipstream"});
		g2.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 0.59f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 1.68f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 7.06f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 2.24f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 2.76f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 3.47f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 10.02f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 138.8f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Directive"});
		g2.Add(new CSGOSkins() { prize = 0.89f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 1.06f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "DGlock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 1.13f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 1.97f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 3.82f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 3.84f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 4.47f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 5.26f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 8.41f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 18.8f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Weasel"});
		g2.Add(new CSGOSkins() { prize = 0.24f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 0.32f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 0.58f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 0.73f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "DMAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 0.68f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 1.13f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 2.8f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Petroglyph"});
		g2.Add(new CSGOSkins() { prize = 0.24f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.23f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.94f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.74f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.76f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.85f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 1.55f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 3.37f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Powercore"});
		g2.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 0.23f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 0.26f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 1.24f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 0.63f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 0.74f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 0.82f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 1.91f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 8.97f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "SG 553",secondname = "Triarch"});
		g2.Add(new CSGOSkins() { prize = 1.92f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 2.27f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 1.76f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 2.96f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 4.45f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 4.19f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 7.73f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 5.01f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 10.2f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 24.2f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AUG",secondname = "Syd Mead"});
		g2.Add(new CSGOSkins() { prize = 1.86f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 2.1f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 1.79f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 3.06f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 5.36f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 4.26f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 5.18f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 5.59f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 7.94f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 21.1f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "MP9",secondname = "Airlock"});
		g2.Add(new CSGOSkins() { prize = 2.76f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 3.06f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 3.22f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 4.8f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 9.42f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 8.3f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 10.7f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 12.2f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 18.1f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 42.9f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Fuel Injector"});
		g2.Add(new CSGOSkins() { prize = 24.6f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 35.7f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 28.4f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 44.2f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 74.9f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 70.4f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 94.7f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 84.1f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 142.7f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 313.6f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Neon Revolution"});
		g2.Add(new CSGOSkins() { prize = 4.96f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 4.78f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 6.72f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 10.3f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 21.8f, type = "Red",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 13.7f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 16.1f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 21.7f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 32.5f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Roll Cage"});
		g2.Add(new CSGOSkins() { prize = 109.1f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Roll Cage"});
	
		g2.Add(new CSGOSkins() { prize = 324, type = "Rare",condition ="Factory New",stattrak = "",firstname = "M9 Bayonet",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 988, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 247, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 326, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 293, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 367, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 138, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "M9 Bayonet",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 330, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 161, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Bright Water"});
		g2.Add(new CSGOSkins() { prize = 248, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Bright Water"});
		g2.Add(new CSGOSkins() { prize = 221, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Karambit",secondname = "Freehand"});
		g2.Add(new CSGOSkins() { prize = 368, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Freehand"});
		g2.Add(new CSGOSkins() { prize = 417, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 897, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 1211, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 413, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 190, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 366, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 161, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 95, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 190, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 171, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Gut Knife",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 285, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 69, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 192, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 93, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 227, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 62, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 120, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 58, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Flip Knife",secondname = "Bright Water"});
		g2.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Bright Water"});
		g2.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Freehand"});
		g2.Add(new CSGOSkins() { prize = 174, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Freehand"});
		g2.Add(new CSGOSkins() { prize = 268, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Flip Knife",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 326, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 133, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 244, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 344, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Autotronic"});
		g2.Add(new CSGOSkins() { prize = 114, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 372, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Black Laminate"});
		g2.Add(new CSGOSkins() { prize = 95, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Bright Water"});
		g2.Add(new CSGOSkins() { prize = 126, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Bright Water"});
		g2.Add(new CSGOSkins() { prize = 228, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Freehand"});
		g2.Add(new CSGOSkins() { prize = 131, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Freehand"});
		g2.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Bayonet",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 375, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Gamma Doppler"});
		g2.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Lore"});
		g2.Add(new CSGOSkins() { prize = 508, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Lore"});

	}
}
