using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class GammaDatabase : MonoBehaviour {
	public List<CSGOSkins> g = new List<CSGOSkins> ();

	void Start () {

		g.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 0.33f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 0.30f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 0.69f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 1.1f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 1.82f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 0.94f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 1.70f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 3.75f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Violent Daimyo"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 1.1f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Carnivore"});
		g.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Exo"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 2.12f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Iron Clad"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.37f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.82f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Harvester"});
		g.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.52f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 1.34f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 1.96f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Ice Cap"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.62f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 1.5f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SG 553",secondname = "Aerial"});
		g.Add(new CSGOSkins() { prize = 2.93f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 2.01f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 2.06f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 2.94f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 11.1f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 7.68f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 8.94f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 12.5f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "Phobos"});
		g.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 0.75f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 1.35f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 1.56f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 1.65f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 1.75f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 2.55f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 5.82f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "AUG",secondname = "Aristocrat"});
		g.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 0.78f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 0.51f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 0.71f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 1.19f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 1.87f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 2.86f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 1.78f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 2.58f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 5.09f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Chopper"});
		g.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 0.44f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 0.53f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 0.74f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 1.46f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 1.26f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 1.4f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 1.74f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 2.8f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 4.97f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Limelight"});
		g.Add(new CSGOSkins() { prize = 0.45f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 0.51f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 0.71f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 1.58f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 1.24f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 1.41f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 1.69f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 2.5f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 9.8f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Reboot"});
		g.Add(new CSGOSkins() { prize = 8.92f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 10.9f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 12.5f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 15.7f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 29.8f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 24.4f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 34.2f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 35.9f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 52.5f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 112.8f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Desolate Space"});
		g.Add(new CSGOSkins() { prize = 1.35f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 1.26f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 1.59f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 2.11f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 4.54f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 4.33f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 6.6f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 14.4f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Bloodsport"});
		g.Add(new CSGOSkins() { prize = 1.48f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 1.57f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 1.39f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 1.82f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 3.19f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 7.15f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 6.15f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 5.83f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 8.63f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 15.7f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial Dragon"});
		g.Add(new CSGOSkins() { prize = 7.86f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 9.51f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 9.86f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 12.4f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 14.8f, type = "Red",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 21.8f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 40.2f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 29.8f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 46.6f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 60.1f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wasteland Rebel"});
		g.Add(new CSGOSkins() { prize = 12.3f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 16.5f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 14.9f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 21.1f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 32.2f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 40.4f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 48.2f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 49.4f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 81.7f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Mecha Industries"});
		g.Add(new CSGOSkins() { prize = 167.2f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Mecha Industries"});
	
		g.Add(new CSGOSkins() { prize = 324, type = "Rare",condition ="Factory New",stattrak = "",firstname = "M9 Bayonet",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 988, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 247, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 326, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 293, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 367, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 138, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "M9 Bayonet",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 330, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 161, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Bright Water"});
		g.Add(new CSGOSkins() { prize = 248, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Bright Water"});
		g.Add(new CSGOSkins() { prize = 221, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Karambit",secondname = "Freehand"});
		g.Add(new CSGOSkins() { prize = 368, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Freehand"});
		g.Add(new CSGOSkins() { prize = 417, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 897, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 1211, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 413, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 190, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 366, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 161, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 95, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Gut Knife",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 190, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 171, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Gut Knife",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 285, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 69, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 192, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 93, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 227, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 62, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 120, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 58, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Flip Knife",secondname = "Bright Water"});
		g.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Bright Water"});
		g.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Freehand"});
		g.Add(new CSGOSkins() { prize = 174, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Freehand"});
		g.Add(new CSGOSkins() { prize = 268, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Flip Knife",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 326, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 133, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 244, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 344, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Autotronic"});
		g.Add(new CSGOSkins() { prize = 114, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 372, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Black Laminate"});
		g.Add(new CSGOSkins() { prize = 95, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Bright Water"});
		g.Add(new CSGOSkins() { prize = 126, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Bright Water"});
		g.Add(new CSGOSkins() { prize = 228, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Freehand"});
		g.Add(new CSGOSkins() { prize = 131, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Freehand"});
		g.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Bayonet",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 375, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Gamma Doppler"});
		g.Add(new CSGOSkins() { prize = 358, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Lore"});
		g.Add(new CSGOSkins() { prize = 508, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Lore"});
	
	}
}

