using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class GlovesDatabase : MonoBehaviour {
	public List<CSGOSkins> gl = new List<CSGOSkins> ();

	void Start () {
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.6f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.91f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 1.58f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Polymer"});
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.70f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.88f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.79f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.91f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 1.36f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 5.78f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Ironwork"});
		gl.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 0.94f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 0.73f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 1.74f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 1.02f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 1.84f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 4.62f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MP7",secondname = "Cirrus"});
		gl.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.59f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.4f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.46f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.93f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 3.19f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Black Sand"});
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.53f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 1.42f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MP9",secondname = "Sand Scale"});
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.46f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.87f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 1.31f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Sonar"});
		gl.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.68f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.51f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.6f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 1.2f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 5.31f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Turf"});
		gl.Add(new CSGOSkins() { prize = 0.29f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 0.69f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 2f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 1.05f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 1.02f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 1.31f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 3.39f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 10.29f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Royal Consorts"});
		gl.Add(new CSGOSkins() { prize = 0.29f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 0.39f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 0.78f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 0.86f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 1.84f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 0.93f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 1.55f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 2.63f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Stinger"});
		gl.Add(new CSGOSkins() { prize = 2.60f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 2.75f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 3.04f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 4.51f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 7.57f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 9.68f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 9.67f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 10.48f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 15.41f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 33f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Flashback"});
		gl.Add(new CSGOSkins() { prize = 0.31f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Gila"});
		gl.Add(new CSGOSkins() { prize = 0.33f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Gila"});
		gl.Add(new CSGOSkins() { prize = 0.56f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Gila"});
		gl.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Gila"});
		gl.Add(new CSGOSkins() { prize = 1.29f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Gila"});
		gl.Add(new CSGOSkins() { prize = 2.19f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Gila"});
		gl.Add(new CSGOSkins() { prize = 2.16f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 3.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 3.2f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 5.29f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 6.63f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 8.04f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 11.9f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 10.2f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 18.5f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 26.7f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Cyrex"});
		gl.Add(new CSGOSkins() { prize = 2.53f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 2.86f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 2.71f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 4.01f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 4.98f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 7.7f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 6.07f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 7.9f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 14.7f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 17.9f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Mecha Industries"});
		gl.Add(new CSGOSkins() { prize = 2.17f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 2.67f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 2.39f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 3.57f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 4.86f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 7.4f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 13.4f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 7.83f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 12.5f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 24.9f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Shallow Grave"});
		gl.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 2.2f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 2.23f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 3.19f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 4.24f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 5.4f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 7.1f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 6.62f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 9.39f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 14.5f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Wasteland Princess"});
		gl.Add(new CSGOSkins() { prize = 18.7f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 23.5f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 25.3f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 33.6f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 40f, type = "Red",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 42.3f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 64f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 66.7f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 109f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 151f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Dragonfire"});
		gl.Add(new CSGOSkins() { prize = 14.9f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 22.6f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 19.4f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 26.1f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 36f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 56.2f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 64.9f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 63.3f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 93.9f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Buzz Kill"});
		gl.Add(new CSGOSkins() { prize = 136f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Buzz Kill"});
	
		gl.Add(new CSGOSkins() { prize = 1181, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Sport Gloves",secondname = "Superconductor"});
		gl.Add(new CSGOSkins() { prize = 375, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Sport Gloves",secondname = "Pandoras Box"});
		gl.Add(new CSGOSkins() { prize = 225, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Sport Gloves",secondname = "Hedge Maze"});
		gl.Add(new CSGOSkins() { prize = 106, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Sport Gloves",secondname = "Arid"});
		gl.Add(new CSGOSkins() { prize = 172, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Specialist Gloves",secondname = "Foundation"});
		gl.Add(new CSGOSkins() { prize = 475, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Specialist Gloves",secondname = "Forest DDPAT"});
		gl.Add(new CSGOSkins() { prize = 178, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Specialist Gloves",secondname = "Emerald Web"});
		gl.Add(new CSGOSkins() { prize = 285, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Specialist Gloves",secondname = "Crimson Kimono"});
		gl.Add(new CSGOSkins() { prize = 220, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Moto Gloves",secondname = "Spearmint"});
		gl.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Moto Gloves",secondname = "Eclipse"});
		gl.Add(new CSGOSkins() { prize = 119, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Moto Gloves",secondname = "Cool Mint"});
		gl.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Moto Gloves",secondname = "Boom!"});
		gl.Add(new CSGOSkins() { prize = 138, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Driver Gloves",secondname = "Lunar Weave"});
		gl.Add(new CSGOSkins() { prize = 134, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Driver Gloves",secondname = "Diamondback"});
		gl.Add(new CSGOSkins() { prize = 288, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Driver Gloves",secondname = "Crimson Weave"});
		gl.Add(new CSGOSkins() { prize = 199, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Driver Gloves",secondname = "Convoy"});
		gl.Add(new CSGOSkins() { prize = 1232, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bloodhound Gloves",secondname = "Snakebite"});
		gl.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bloodhound Gloves",secondname = "Charred"});
		gl.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bloodhound Gloves",secondname = "Guerrilla"});
		gl.Add(new CSGOSkins() { prize = 238, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Bloodhound Gloves",secondname = "Bronzed"});
		gl.Add(new CSGOSkins() { prize = 146, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Hand Wraps",secondname = "Badlands"});
		gl.Add(new CSGOSkins() { prize = 229, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Hand Wraps",secondname = "Leather"});
		gl.Add (new CSGOSkins () {prize = 192,type = "Rare",condition = "Field-Tested",stattrak = "",firstname = "Hand Wraps",secondname = "Slaughter"});
	}
}
