using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class MirageDatabase : MonoBehaviour {
	public List<CSGOSkins> m = new List<CSGOSkins> ();

	void Start () {
	
		m.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.14f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.97f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.32f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.39f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.27f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.50f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 3.98f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "P250",secondname = "Bone Mask"});
		m.Add(new CSGOSkins() { prize = 0.16f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.09f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.26f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 1.92f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.38f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.45f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.30f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.58f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 7.74f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "Five-Seven",secondname = "Contractor"});
		m.Add(new CSGOSkins() { prize = 0.09f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.14f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 1.29f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.29f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.38f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.25f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "PAUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.43f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 4.85f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "AUG",secondname = "Colony"});
		m.Add(new CSGOSkins() { prize = 0.10f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.13f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.13f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 1.21f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.16f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.14f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 2.42f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "G3SG1",secondname = "Safari Mesh"});
		m.Add(new CSGOSkins() { prize = 0.08f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.20f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.07f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.13f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.64f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.30f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.17f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.41f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 3.39f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "P90",secondname = "Scorched"});
		m.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.49f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.09f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.32f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.56f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.68f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.29f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.46f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 0.99f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "Galil AR",secondname = "Hunting Blind"});
		m.Add(new CSGOSkins() { prize = 1.37f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 1.00f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.39f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.72f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.79f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.53f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.49f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.22f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.39f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 1.18f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Negev",secondname = "CaliCamo"});
		m.Add(new CSGOSkins() { prize = 0.46f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 0.74f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 0.49f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 0.68f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 6.82f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 1.54f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 2.66f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 1.33f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 3.76f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 22.75f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Tropical Storm"});
		m.Add(new CSGOSkins() { prize = 0.78f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.51f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.59f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.66f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.68f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.80f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 1.36f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.58f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.70f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 2.24f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "SG 553",secondname = "Gator Mesh"});
		m.Add(new CSGOSkins() { prize = 0.48f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 0.68f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 0.44f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 0.91f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 9.25f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 2.22f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 2.43f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 1.80f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 4.08f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 48.64f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Groundwater"});
		m.Add(new CSGOSkins() { prize = 0.52f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 0.87f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 0.51f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 0.66f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 2.05f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 0.77f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 0.91f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 0.73f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 1.93f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 16.74f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MP7",secondname = "Orange Peel"});
		m.Add(new CSGOSkins() { prize = 3.06f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 1.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 1.14f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 2.54f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 5.50f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 1.93f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 3.76f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 6.94f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MAC-10",secondname = "Amber Fade"});
		m.Add(new CSGOSkins() { prize = 13.65f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Blaze"});
		m.Add(new CSGOSkins() { prize = 6.60f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Blaze"});
		m.Add(new CSGOSkins() { prize = 35.49f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Blaze"});
		m.Add(new CSGOSkins() { prize = 22.84f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Blaze"});
		m.Add(new CSGOSkins() { prize = 6.94f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Hot Rod"});
		m.Add(new CSGOSkins() { prize = 3.38f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Hot Rod"});
		m.Add(new CSGOSkins() { prize = 16.46f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP9",secondname = "Hot Rod"});
		m.Add(new CSGOSkins() { prize = 13.56f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MP9",secondname = "Hot Rod"});
		m.Add(new CSGOSkins() { prize = 0.34f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 0.91f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 0.35f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 2.89f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 31.12f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 3.10f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 3.19f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 4.24f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 12.62f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Bulldozer"});
		m.Add(new CSGOSkins() { prize = 47.71f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Bulldozer"});
	}
	}
