using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class NukeDatabase : MonoBehaviour {
	public List<CSGOSkins> n = new List<CSGOSkins> ();

	void Start () {
	
		n.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.33f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 3.65f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.34f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.24f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.67f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 6.43f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "PP-Bizon",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.22f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.44f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.17f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.33f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 4.81f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.32f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.16f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.39f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 13.58f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 1.10f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.31f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 3.01f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.25f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.27f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 0.67f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 11.46f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Irradiated Alert"});
		n.Add(new CSGOSkins() { prize = 1.12f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 1.08f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.84f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.61f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 22.40f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.98f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 1.11f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.95f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.29f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 83.34f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "XM1014",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 1.11f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 1.00f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.98f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.88f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 25.33f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.34f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.11f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.35f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 5.63f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 50.39f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.78f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.78f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 0.77f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.29f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 16.64f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 1.43f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 2.77f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 1.32f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 3.66f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 30.72f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "P90",secondname = "Fallout Warning"});
		n.Add(new CSGOSkins() { prize = 3.92f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 4.36f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 3.50f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 12.53f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 123.87f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 7.48f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 12.84f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 10.37f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 32.12f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 295.28f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "M4A4",secondname = "Radiation Hazard"});
		n.Add(new CSGOSkins() { prize = 0.02f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.02f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.02f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.02f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.08f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.17f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.19f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.15f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 5.39f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "P250",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 9.61f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 9.98f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 9.99f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 27.66f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 360.79f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 39.09f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 44.11f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 68.13f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 373.40f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Nuclear Threat"});
		n.Add(new CSGOSkins() { prize = 524.87f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "Tec-9",secondname = "Nuclear Threat"});
	
	}
	}
