using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class OverpassDatabase : MonoBehaviour {
	public List<CSGOSkins> o = new List<CSGOSkins> ();

	void Start () {
		o.Add(new CSGOSkins() { prize = 0.09f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.05f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.45f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.16f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.15f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.20f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 3.18f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "Sawed-Off",secondname = "Sage Spray"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.05f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.41f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.33f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.55f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.29f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.58f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 4.95f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "UMP-45",secondname = "Scorched"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.37f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.13f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.21f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 4.64f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "M249",secondname = "Contrast Spray"});
		o.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.05f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "SStorm"});
		o.Add(new CSGOSkins() { prize = 0.39f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.19f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.18f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.14f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.30f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 4.02f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "MAG-7",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.04f, type = "Grey",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.03f, type = "Grey",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.06f, type = "Grey",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.51f, type = "Grey",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.26f, type = "Grey",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.38f, type = "Grey",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.26f, type = "Grey",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.70f, type = "Grey",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 5.24f, type = "Grey",condition ="Factory New",stattrak = "Souvenir", firstname = "MP9",secondname = "Storm"});
		o.Add(new CSGOSkins() { prize = 0.18f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 0.18f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 0.17f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 0.37f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 2.87f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 3.09f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 3.13f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 2.54f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 6.44f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 73.94f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Desert Eagle",secondname = "Urban DDPAT"});
		o.Add(new CSGOSkins() { prize = 0.14f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 0.18f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 0.16f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 0.35f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 2.62f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 1.30f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 2.17f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 1.14f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 5.83f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 366.55f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "MP7",secondname = "Gunsmoke"});
		o.Add(new CSGOSkins() { prize = 0.16f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 0.17f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 0.17f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 0.35f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 5.35f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 2.82f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 4.41f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 3.20f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 7.74f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 188.34f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "Glock-18",secondname = "Night"});
		o.Add(new CSGOSkins() { prize = 0.15f, type = "White Blue",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 0.15f, type = "White Blue",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 0.16f, type = "White Blue",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 0.23f, type = "White Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 1.28f, type = "White Blue",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 0.68f, type = "White Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 1.16f, type = "White Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 0.68f, type = "White Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 1.26f, type = "White Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 34.05f, type = "White Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "P2000",secondname = "Grassland"});
		o.Add(new CSGOSkins() { prize = 1.40f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 1.40f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 1.56f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 1.63f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 6.95f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 4.24f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 5.46f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 3.90f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 9.17f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 160.98f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "CZ75-Auto",secondname = "Nitro"});
		o.Add(new CSGOSkins() { prize = 1.70f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 1.69f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 1.43f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 1.73f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 2.40f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 2.06f, type = "Blue",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 2.09f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 1.35f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 2.27f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 5.09f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "XM1014",secondname = "VariCamo Blue"});
		o.Add(new CSGOSkins() { prize = 1.30f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 1.39f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 1.58f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 2.93f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 22.94f, type = "Blue",condition ="Well-Worn",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 10.35f, type = "Blue",condition ="Field-Tested",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 22.45f, type = "Blue",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 30.98f, type = "Blue",condition ="Factory New",stattrak = "Souvenir", firstname = "SSG 08",secondname = "Detour"});
		o.Add(new CSGOSkins() { prize = 7.19f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 9.80f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 8.75f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 11.93f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 42.52f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 49.75f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 207.56f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 82.70f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 340.28f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 1000.00f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "AWP",secondname = "Pink DDPAT"});
		o.Add(new CSGOSkins() { prize = 5.06f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 5.34f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 5.70f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 7.64f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 13.97f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 62.79f, type = "Purple",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 33.46f, type = "Purple",condition ="Well-Worn",stattrak = "Souvenir", firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 65.84f, type = "Purple",condition ="Field-Tested",stattrak = "Souvenir", firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 53.63f, type = "Purple",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 175.16f, type = "Purple",condition ="Factory New",stattrak = "Souvenir", firstname = "USP-S",secondname = "Road Rash"});
		o.Add(new CSGOSkins() { prize = 12.52f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 17.09f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 22.46f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 35.49f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 88.79f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 210.78f, type = "Pink",condition ="Battle-Scared",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 345.81f, type = "Pink",condition ="Well-Worn",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 500.27f, type = "Pink",condition ="Field-Tested",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 1000.50f, type = "Pink",condition ="Minimal Wear",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Master Piece"});
		o.Add(new CSGOSkins() { prize = 1700.98f, type = "Pink",condition ="Factory New",stattrak = "Souvenir", firstname = "M4A1-S",secondname = "Master Piece"});
	}
	}
