using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class PhoenixDatabase : MonoBehaviour {
	public List<CSGOSkins> p = new List<CSGOSkins> ();

	void Start () {
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 1.52f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Corporal"});
		p.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.20f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.37f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Negev",secondname = "Terrain"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.54f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 1.06f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Tec9",secondname = "Sandstorm"});
		p.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Heaven Guard"});
		p.Add(new CSGOSkins() { prize = 0.3f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 0.31f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 1.05f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 0.92f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 1.03f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 1.46f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 2.17f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 3.89f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Heat"});
		p.Add(new CSGOSkins() { prize = 0.31f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 0.57f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 0.3f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 0.90f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 1.4f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 0.97f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 3.54f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SG 553",secondname = "Pulse"});
		p.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 0.32f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 0.30f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 0.75f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 0.87f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 1.09f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 0.97f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 3.31f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Sergant"});
		p.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Guardian"});
		p.Add(new CSGOSkins() { prize = 0.76f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Guardian"});
		p.Add(new CSGOSkins() { prize = 1.07f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Guardian"});
		p.Add(new CSGOSkins() { prize = 2.56f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Guardian"});
		p.Add(new CSGOSkins() { prize = 3.9f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Guardian"});
		p.Add(new CSGOSkins() { prize = 5.2f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Guardian"});
		p.Add(new CSGOSkins() { prize = 3.01f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 5.39f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 4.94f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 13.88f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 9.19f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 16.47f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 15.99f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 86.24f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Redline"});
		p.Add(new CSGOSkins() { prize = 1.81f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 1.81f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 1.86f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 2.58f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 5.04f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 4.99f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 4.59f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 7.79f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Trigon"});
		p.Add(new CSGOSkins() { prize = 2.2f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Antique"});
		p.Add(new CSGOSkins() { prize = 1.99f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Antique"});
		p.Add(new CSGOSkins() { prize = 2.87f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Antique"});
		p.Add(new CSGOSkins() { prize = 4.94f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Antique"});
		p.Add(new CSGOSkins() { prize = 5.55f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Antique"});
		p.Add(new CSGOSkins() { prize = 9.49f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Antique"});
		p.Add(new CSGOSkins() { prize = 16.64f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AWP",secondname = "Asiimov"});
		p.Add(new CSGOSkins() { prize = 21.21f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Asiimov"});
		p.Add(new CSGOSkins() { prize = 24.86f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Asiimov"});
		p.Add(new CSGOSkins() { prize = 44.99f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AWP",secondname = "Asiimov"});
		p.Add(new CSGOSkins() { prize = 59.88f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AWP",secondname = "Asiimov"});
		p.Add(new CSGOSkins() { prize = 70.85f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Asiimov"});
		p.Add(new CSGOSkins() { prize = 1.27f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 1.44f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 1.14f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 1.18f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 1.88f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 3.9f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 4.19f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 3.35f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 5.26f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AUG",secondname = "Chameleon"});
		p.Add(new CSGOSkins() { prize = 8.25f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AUG",secondname = "Chameleon"});
	
		p.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		p.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		p.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		p.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		p.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		p.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		p.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		p.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		p.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		p.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		p.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		p.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		p.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		p.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		p.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		p.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		p.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		p.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		p.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		p.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		p.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		p.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		p.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		p.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		p.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		p.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		p.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		p.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		p.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		p.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		p.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		p.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		p.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		p.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		p.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		p.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		p.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		p.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		p.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		p.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		p.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		p.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
	}
