using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class RevolverDatabase : MonoBehaviour {
	public List<CSGOSkins> r = new List<CSGOSkins> ();

	void Start () {
	
		r.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 2.19f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 15.2f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 1.16f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.79f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 1.24f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 3.14f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "AUG",secondname = "Ricochet"});
		r.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 2.08f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 1.48f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 1.97f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 3.02f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Corinthian"});
		r.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Imperial"});
		r.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Imperial"});
		r.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Imperial"});
		r.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial"});
		r.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial"});
		r.Add(new CSGOSkins() { prize = 0.98f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Imperial"});
		r.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.33f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.57f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 1.13f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Yorick"});
		r.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.26f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.62f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.99f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Outbreak"});
		r.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 0.45f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 0.87f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 1.95f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 1.18f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 1.31f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 1.69f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 3.41f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 9.56f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Fuel Rod"});
		r.Add(new CSGOSkins() { prize = 0.37f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 0.93f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 1.76f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 1.13f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 1.37f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 1.48f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 3.58f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 8.25f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Negev",secondname = "Power Loader"});
		r.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 0.42f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 0.36f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 0.9f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 2.21f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 1.18f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 1.57f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 1.81f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 5.51f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 12.96f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Retrobution"});
		r.Add(new CSGOSkins() { prize = 0.42f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 0.49f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 0.78f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 2.12f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 1.54f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 1.83f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 2.50f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 3.92f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 12.43f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "SG 553",secondname = "Tiger Moth"});
		r.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 0.63f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 1.46f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 3.06f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 2.51f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 2.94f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 3.4f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 7.48f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 15.95f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Avalanche"});
		r.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 0.78f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 1.13f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 2.54f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 2.44f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 1.69f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 3.35f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 5.27f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "XM1014",secondname = "Teclu Burner"});
		r.Add(new CSGOSkins() { prize = 6.05f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 9.12f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 8.52f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 11.28f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 18.74f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 18.39f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 32.73f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 25.08f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 36.48f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 55.78f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Point Disarray"});
		r.Add(new CSGOSkins() { prize = 1.1f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 1.03f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 0.92f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 1.48f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 3.97f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 2.78f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 3.22f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 3.72f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 7.63f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 45.14f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Shapewood"});
		r.Add(new CSGOSkins() { prize = 1.1f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 0.94f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 0.97f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 13.71f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 3.34f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 3.68f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 3.75f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 342.13f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "The Executioner"});
		r.Add(new CSGOSkins() { prize = 2.8f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "R8 Revolver",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 1.67f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "R8 Revolver",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 2.4f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "R8 Revolver",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 5.11f, type = "Red",condition ="Factory New",stattrak = "",firstname = "R8 Revolver",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 8.68f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Fade"});	
		r.Add(new CSGOSkins() { prize = 11.61f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 19.02f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "R8 Revolver",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 4.07f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 6.65f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 5.2f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 12.56f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 31.4f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 22.7f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 39.74f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 22.57f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Royal Paladin"});	
		r.Add(new CSGOSkins() { prize = 60.1f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Royal Paladin"});
		r.Add(new CSGOSkins() { prize = 270.19f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Royal Paladin"});
	
		r.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		r.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		r.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		r.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		r.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		r.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		r.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		r.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		r.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		r.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		r.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		r.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		r.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		r.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		r.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		r.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		r.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		r.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		r.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		r.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		r.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		r.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		r.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		r.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		r.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		r.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		r.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		r.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		r.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		r.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		r.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		r.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		r.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		r.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		r.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		r.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});
	}
}
