using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class ShadowDatabase : MonoBehaviour {
	public List<CSGOSkins> s = new List<CSGOSkins> ();

	void Start () {
	
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.57f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 4.02f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Dualing Dragons"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.42f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 1.0f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Survivor Z"});
		s.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.65f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 1.15f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.59f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 2.42f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Wraiths"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.62f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Rangeen"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.55f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Cobalt Core"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.66f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Green Marine"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.19f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.74f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "XM1014",secondname = "Scumbria"});
		s.Add(new CSGOSkins() { prize = 0.33f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 0.41f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 0.57f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 1.49f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 0.86f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 1.04f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 0.99f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 2.03f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 7.39f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Stone Cold"});
		s.Add(new CSGOSkins() { prize = 0.35f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 0.37f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 0.36f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 1.08f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 0.87f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 1.04f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 1.49f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 4.05f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "M249",secondname = "Nebula Crusader"});
		s.Add(new CSGOSkins() { prize = 0.35f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 0.44f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 0.36f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 0.47f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 0.95f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 1.04f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 1.38f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 1.1f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 1.76f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 3.44f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MP7",secondname = "Special Delivery"});
		s.Add(new CSGOSkins() { prize = 0.34f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 0.65f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 1.63f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 1.15f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 1.3f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 1.24f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 2.3f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 8.04f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Wingshot"});
		s.Add(new CSGOSkins() { prize = 5.07f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 6.93f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 6.88f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 10.2f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 19.4f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 12.2f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 16.5f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 19.2f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 31.1f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 65.0f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Frontside Misty"});
		s.Add(new CSGOSkins() { prize = 1.73f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 1.71f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 1.8f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 2.47f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 4.55f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 5.02f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 5.66f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 5.41f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 9.39f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 21.9f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Flux"});
		s.Add(new CSGOSkins() { prize = 1.78f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 1.91f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 1.87f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 2.4f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 4.31f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 5.2f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 5.74f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 5.58f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 10.2f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 17.2f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Big Iron"});
		s.Add(new CSGOSkins() { prize = 8.67f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 9.88f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 11.3f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 16.0f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 30.5f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 24.9f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 29.7f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 33.5f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 65.4f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 113, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Golden Coil"});
		s.Add(new CSGOSkins() { prize = 16, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 17.7f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 19.7f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 27.0f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 53.5f, type = "Red",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 53.9f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 51.5f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 67.6f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 97.4f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Kill Confirmed"});
		s.Add(new CSGOSkins() { prize = 211, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Kill Confirmed"});

		s.Add(new CSGOSkins() { prize = 119, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Shadow Daggers",secondname = "Crimson Web"});
		s.Add(new CSGOSkins() { prize = 1322, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Crimson Web"});
		s.Add(new CSGOSkins() { prize = 139, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Shadow Daggers",secondname = "Fade"});
		s.Add(new CSGOSkins() { prize = 177, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Fade"});
		s.Add(new CSGOSkins() { prize = 44, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Shadow Daggers",secondname = "Forest DDPAT"});
		s.Add(new CSGOSkins() { prize = 56, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Forest DDPAT"});
		s.Add(new CSGOSkins() { prize = 58, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Shadow Daggers",secondname = "Case Hardened"});
		s.Add(new CSGOSkins() { prize = 78, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Case Hardened"});
		s.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Shadow Daggers",secondname = "Safari Mesh"});
		s.Add(new CSGOSkins() { prize = 52, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Safari Mesh"});
		s.Add(new CSGOSkins() { prize = 41, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Shadow Daggers",secondname = "Scorched"});
		s.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Scorched"});
		s.Add(new CSGOSkins() { prize = 77, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Shadow Daggers",secondname = "Slaughter"});
		s.Add(new CSGOSkins() { prize = 141, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Slaughter"});
		s.Add(new CSGOSkins() { prize = 47, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Shadow Daggers",secondname = "Stained"});
		s.Add(new CSGOSkins() { prize = 79, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Shadow Daggers",secondname = "Stained"});

	}
}
