using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class VanguardDatabase : MonoBehaviour {
	public List<CSGOSkins> v = new List<CSGOSkins> ();

	void Start () {
		v.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Urban Hazard"});
		v.Add(new CSGOSkins() { prize = 0.37f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Urban Hazard"});
		v.Add(new CSGOSkins() { prize = 0.45f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Urban Hazard"});
		v.Add(new CSGOSkins() { prize = 1.17f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Urban Hazard"});
		v.Add(new CSGOSkins() { prize = 1.39f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Urban Hazard"});
		v.Add(new CSGOSkins() { prize = 1.77f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Urban Hazard"});
		v.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "G3SG1",secondname = "Murky"});
		v.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "G3SG1",secondname = "Murky"});
		v.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "G3SG1",secondname = "Murky"});
		v.Add(new CSGOSkins() { prize = 0.54f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Murky"});
		v.Add(new CSGOSkins() { prize = 0.59f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Murky"});
		v.Add(new CSGOSkins() { prize = 0.83f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "G3SG1",secondname = "Murky"});
		v.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 1.1f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.52f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 4.87f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Firestarter"});
		v.Add(new CSGOSkins() { prize = 0.93f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.20f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 1.03f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.37f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.58f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 1.06f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MP9",secondname = "Dart"});
		v.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "UMP-45",secondname = "Delusion"});
		v.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "UMP-45",secondname = "Delusion"});
		v.Add(new CSGOSkins() { prize = 1.58f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "UMP-45",secondname = "Delusion"});
		v.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Delusion"});
		v.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Delusion"});
		v.Add(new CSGOSkins() { prize = 4.91f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "UMP-45",secondname = "Delusion"});
		v.Add(new CSGOSkins() { prize = 0.56f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Grinder"});
		v.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Grinder"});
		v.Add(new CSGOSkins() { prize = 0.55f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Grinder"});
		v.Add(new CSGOSkins() { prize = 2.45f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Grinder"});
		v.Add(new CSGOSkins() { prize = 2.36f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Grinder"});
		v.Add(new CSGOSkins() { prize = 3.76f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Grinder"});
		v.Add(new CSGOSkins() { prize = 1.21f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 1.93f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 1.41f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 1.14f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 2.42f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 5.95f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 5.72f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 5.25f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 6.04f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 11.65f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Basilisk"});
		v.Add(new CSGOSkins() { prize = 1.14f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 2.25f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 1.14f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 1.67f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 4.1f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 4.19f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 6.47f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 4.25f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 6.08f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 13.88f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "Griffin"});
		v.Add(new CSGOSkins() { prize = 0.23f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.24f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.24f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.26f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.56f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.62f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.57f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 0.76f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 1.36f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 3.33f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "Highwayman"});
		v.Add(new CSGOSkins() { prize = 1.45f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 1.99f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 1.5f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 2.09f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 4.63f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 5.15f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 5.98f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 5.35f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 9.19f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 26.16f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Cartel"});
		v.Add(new CSGOSkins() { prize = 1.81f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 1.55f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 1.39f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 1.72f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 4.57f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 4.65f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 4.66f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 5.39f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 9.76f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 29.17f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Cardiac"});
		v.Add(new CSGOSkins() { prize = 1.76f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 1.86f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 1.58f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 2.18f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 4.8f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 15.54f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 9.98f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 6.42f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 8.55f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 20.69f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "XM1014",secondname = "Tranquility"});
		v.Add(new CSGOSkins() { prize = 13.3f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 16.49f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 13.88f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 20.15f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 76.72f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 44.75f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 62.70f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 55.64f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 80.81f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 360, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Wasteland Rebel"});
		v.Add(new CSGOSkins() { prize = 4.49f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 4.50f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 4.49f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 5.55f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 9.23f, type = "Red",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 20.35f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 24.45f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 22.79f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 35.36f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Fire Elemental"});
		v.Add(new CSGOSkins() { prize = 62.85f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Fire Elemental"});
	
		v.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		v.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		v.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		v.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		v.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		v.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		v.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		v.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		v.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		v.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		v.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		v.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		v.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		v.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		v.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		v.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		v.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		v.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		v.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		v.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		v.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		v.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		v.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		v.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		v.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		v.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		v.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		v.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		v.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		v.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		v.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		v.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		v.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		v.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		v.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		v.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		v.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		v.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		v.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		v.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		v.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		v.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
}
