using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Weapon2Database : MonoBehaviour {
	public List<CSGOSkins> w2 = new List<CSGOSkins> ();

	void Start () {
		w2.Add(new CSGOSkins() { prize = 1.32f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Blood Tiger"});
		w2.Add(new CSGOSkins() { prize = 1.31f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Blood Tiger"});
		w2.Add(new CSGOSkins() { prize = 1.81f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Blood Tiger"});
		w2.Add(new CSGOSkins() { prize = 5.88f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Blood Tiger"});
		w2.Add(new CSGOSkins() { prize = 5.79f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Blood Tiger"});
		w2.Add(new CSGOSkins() { prize = 8.45f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Blood Tiger"});
		w2.Add(new CSGOSkins() { prize = 0.59f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Hive"});
		w2.Add(new CSGOSkins() { prize = 0.66f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Hive"});
		w2.Add(new CSGOSkins() { prize = 0.83f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Hive"});
		w2.Add(new CSGOSkins() { prize = 1.32f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Hive"});
		w2.Add(new CSGOSkins() { prize = 1.50f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Hive"});
		w2.Add(new CSGOSkins() { prize = 2.16f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Hive"});
		w2.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 0.63f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 0.75f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 2.07f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 1.51f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 2.28f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Hexane"});
		w2.Add(new CSGOSkins() { prize = 0.76f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Blue Titanium"});
		w2.Add(new CSGOSkins() { prize = 2.23f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Blue Titanium"});
		w2.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 0.66f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 2.52f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 0.72f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 0.88f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 0.91f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 1.63f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 20.50f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SCAR-20",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 2.27f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Hypnotic"});
		w2.Add(new CSGOSkins() { prize = 0.85f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Hypnotic"});
		w2.Add(new CSGOSkins() { prize = 6.11f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP9",secondname = "Hypnotic"});
		w2.Add(new CSGOSkins() { prize = 3.78f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MP9",secondname = "Hypnotic"});
		w2.Add(new CSGOSkins() { prize = 0.79f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Hemoglobin"});
		w2.Add(new CSGOSkins() { prize = 0.78f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Hemoglobin"});
		w2.Add(new CSGOSkins() { prize = 0.80f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Hemoglobin"});
		w2.Add(new CSGOSkins() { prize = 3.00f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Hemoglobin"});
		w2.Add(new CSGOSkins() { prize = 2.58f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Hemoglobin"});
		w2.Add(new CSGOSkins() { prize = 3.15f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Hemoglobin"});
		w2.Add(new CSGOSkins() { prize = 1.94f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 2.05f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 2.17f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 3.19f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 8.18f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 5.88f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 7.10f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 7.87f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 12.94f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 41.80f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 0.90f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Graphite"});
		w2.Add(new CSGOSkins() { prize = 0.66f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Graphite"});
		w2.Add(new CSGOSkins() { prize = 3.63f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Graphite"});
		w2.Add(new CSGOSkins() { prize = 2.80f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Graphite"});
		w2.Add(new CSGOSkins() { prize = 5.45f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Serum"});
		w2.Add(new CSGOSkins() { prize = 5.21f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Serum"});
		w2.Add(new CSGOSkins() { prize = 7.83f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Serum"});
		w2.Add(new CSGOSkins() { prize = 18.21f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Serum"});
		w2.Add(new CSGOSkins() { prize = 16.99f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Serum"});
		w2.Add(new CSGOSkins() { prize = 25.48f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Serum"});
		w2.Add(new CSGOSkins() { prize = 4.83f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P90",secondname = "Cold Blooded"});
		w2.Add(new CSGOSkins() { prize = 3.99f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P90",secondname = "Cold Blooded"});
		w2.Add(new CSGOSkins() { prize = 18.58f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P90",secondname = "Cold Blooded"});
		w2.Add(new CSGOSkins() { prize = 16.01f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P90",secondname = "Cold Blooded"});
		w2.Add(new CSGOSkins() { prize = 15.90f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Blood in the Water"});
		w2.Add(new CSGOSkins() { prize = 16.70f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Blood in the Water"});
		w2.Add(new CSGOSkins() { prize = 22.49f, type = "Red",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Blood in the Water"});
		w2.Add(new CSGOSkins() { prize = 63.36f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Blood in the Water"});
		w2.Add(new CSGOSkins() { prize = 81.14f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Blood in the Water"});
		w2.Add(new CSGOSkins() { prize = 207.17f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Blood in the Water"});

		w2.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		w2.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		w2.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		w2.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		w2.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		w2.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		w2.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		w2.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		w2.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		w2.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		w2.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		w2.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		w2.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		w2.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		w2.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		w2.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		w2.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		w2.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		w2.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		w2.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		w2.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		w2.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		w2.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		w2.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		w2.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		w2.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		w2.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		w2.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		w2.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		w2.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		w2.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		w2.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		w2.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		w2.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		w2.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		w2.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
}
