using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class Weapon3Database : MonoBehaviour {
	public List<CSGOSkins> w3 = new List<CSGOSkins> ();

	void Start () {
	
		w3.Add(new CSGOSkins() { prize = 0.18f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.21f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 4.62f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.44f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 2.02f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 119.63f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.43f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.49f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.51f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.37f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.77f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 1.70f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "P2000",secondname = "Red FragCam"});
		w3.Add(new CSGOSkins() { prize = 0.46f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.31f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.11f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.85f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 1.13f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 2.77f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Panther"});
		w3.Add(new CSGOSkins() { prize = 1.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 1.67f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 1.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 1.90f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 4.44f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 4.40f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 7.98f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 5.05f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 8.60f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 27.87f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Stainless"});
		w3.Add(new CSGOSkins() { prize = 0.41f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 0.33f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 0.57f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 4.09f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 1.91f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 3.37f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 1.99f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 3.74f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 26.88f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Blue Fissure"});
		w3.Add(new CSGOSkins() { prize = 0.52f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Tread Plate"});
		w3.Add(new CSGOSkins() { prize = 0.32f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Tread Plate"});
		w3.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Tread Plate"});
		w3.Add(new CSGOSkins() { prize = 1.82f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tread Plate"});
		w3.Add(new CSGOSkins() { prize = 1.82f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tread Plate"});
		w3.Add(new CSGOSkins() { prize = 1.95f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Tread Plate"});
		w3.Add(new CSGOSkins() { prize = 0.39f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Titanium Bit"});
		w3.Add(new CSGOSkins() { prize = 0.39f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Titanium Bit"});
		w3.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Titanium Bit"});
		w3.Add(new CSGOSkins() { prize = 2.11f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Titanium Bit"});
		w3.Add(new CSGOSkins() { prize = 1.95f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Titanium Bit"});
		w3.Add(new CSGOSkins() { prize = 2.45f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Titanium Bit"});
		w3.Add(new CSGOSkins() { prize = 0.87f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 1.25f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 0.45f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 0.89f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 2.97f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 3.28f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 9.83f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 3.47f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 5.87f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 22.78f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Heirloom"});
		w3.Add(new CSGOSkins() { prize = 0.78f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Copper Galaxy"});
		w3.Add(new CSGOSkins() { prize = 0.96f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Copper Galaxy"});
		w3.Add(new CSGOSkins() { prize = 1.01f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Copper Galaxy"});
		w3.Add(new CSGOSkins() { prize = 2.67f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Copper Galaxy"});
		w3.Add(new CSGOSkins() { prize = 5.58f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Copper Galaxy"});
		w3.Add(new CSGOSkins() { prize = 7.45f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Copper Galaxy"});
		w3.Add(new CSGOSkins() { prize = 1.67f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 1.41f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 1.37f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 2.06f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 45.60f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 4.87f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 7.77f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 13.39f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "The Fuschia Is Now"});
		w3.Add(new CSGOSkins() { prize = 2.31f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Undertow"});
		w3.Add(new CSGOSkins() { prize = 1.99f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Undertow"});
		w3.Add(new CSGOSkins() { prize = 2.48f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Undertow"});
		w3.Add(new CSGOSkins() { prize = 6.39f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Undertow"});
		w3.Add(new CSGOSkins() { prize = 9.75f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Undertow"});
		w3.Add(new CSGOSkins() { prize = 15.04f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Undertow"});
		w3.Add(new CSGOSkins() { prize = 1.76f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 2.45f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 1.99f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 2.73f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 6.19f, type = "Red",condition ="Factory New",stattrak = "",firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 12.76f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 25.04f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 13.99f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 32.95f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Victoria"});
		w3.Add(new CSGOSkins() { prize = 100.18f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "CZ75-Auto",secondname = "Victoria"});

		w3.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		w3.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		w3.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		w3.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		w3.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		w3.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		w3.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		w3.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		w3.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		w3.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		w3.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		w3.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		w3.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		w3.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		w3.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		w3.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		w3.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		w3.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		w3.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		w3.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		w3.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		w3.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		w3.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		w3.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		w3.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		w3.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		w3.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		w3.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		w3.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		w3.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		w3.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		w3.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		w3.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		w3.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		w3.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		w3.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		w3.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		w3.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		w3.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
	}
