using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class WildfireDatabase : MonoBehaviour {
	public List<CSGOSkins> wi = new List<CSGOSkins> ();

	void Start () {
	
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.1f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.39f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.56f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 2.0f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Photic Zone"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 1.46f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Cartel"});
		wi.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.35f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.2f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.37f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.67f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "MAC-10",secondname = "Lapis Gator"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.7f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.47f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.97f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 5.54f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "SSG 08",secondname = "Necropos"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.08f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.3f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.35f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.64f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 2.65f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Tec-9",secondname = "Jambiya"});
		wi.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 0.14f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 0.17f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 1.01f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 1.21f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 1.16f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 1.26f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 1.82f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 6.88f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "USP-S",secondname = "Lead Conduit"});
		wi.Add(new CSGOSkins() { prize = 0.38f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 0.87f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 0.48f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 0.91f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 2.47f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 1.51f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 2.75f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 1.81f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 3.45f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 10.4f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Valence"});
		wi.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 0.27f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 0.36f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 0.73f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 1.07f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 1.88f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 1.11f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 2.35f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 3.97f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Triumvirate"});
		wi.Add(new CSGOSkins() { prize = 0.3f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 0.33f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 0.36f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 0.7f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 1.99f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 1.91f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 2.01f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 2.22f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 4.39f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 12.6f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Glock-18",secondname = "Royal Legion"});
		wi.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 0.28f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 0.37f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 0.67f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 1.26f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 1.08f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 1.61f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 3.22f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MAG-7",secondname = "Praetorian"});
		wi.Add(new CSGOSkins() { prize = 0.53f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 0.25f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 0.43f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 0.73f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 1.97f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 1.18f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 1.88f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 3.16f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MP7",secondname = "Impire"});
		wi.Add(new CSGOSkins() { prize = 2.41f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 2.88f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 3.22f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 5.01f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 10.2f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 10.3f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 11.1f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 12.4f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 20.8f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 41.0f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "AWP",secondname = "Elite Build"});
		wi.Add(new CSGOSkins() { prize = 2.39f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 4.59f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 2.78f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 4.49f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 8.81f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 11.5f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 18.7f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 13.3f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 19.5f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 45.5f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Desert Eagle",secondname = "Kumicho Dragon"});
		wi.Add(new CSGOSkins() { prize = 1.78f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 1.91f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 1.76f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 2.52f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 4.6f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 5.26f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 6.97f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 6.9f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 9.37f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 20.1f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Hyper Beast"});
		wi.Add(new CSGOSkins() { prize = 16.1f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 18.5f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 22.3f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 28.0f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 51.8f, type = "Red",condition ="Factory New",stattrak = "",firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 54, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 66, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 74, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 105, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 252, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "AK-47",secondname = "Fuel Injector"});
		wi.Add(new CSGOSkins() { prize = 2.98f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 3.84f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 2.99f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 4.94f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 7.91f, type = "Red",condition ="Factory New",stattrak = "",firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 12.5f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 24.7f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 14.5f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 27.8f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A4",secondname = "The Battlestar"});
		wi.Add(new CSGOSkins() { prize = 40.0f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A4",secondname = "The Battlestar"});	
	
		wi.Add(new CSGOSkins() { prize = 78, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bowie Knife",secondname = "Blue Steel"});
		wi.Add(new CSGOSkins() { prize = 162, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Blue Steel"});
		wi.Add(new CSGOSkins() { prize = 52, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bowie Knife",secondname = "Urban Masked"});
		wi.Add(new CSGOSkins() { prize = 68, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Urban Masked"});
		wi.Add(new CSGOSkins() { prize = 99, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bowie Knife",secondname = "Crimson Web"});
		wi.Add(new CSGOSkins() { prize = 562, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Crimson Web"});
		wi.Add(new CSGOSkins() { prize = 284, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bowie Knife",secondname = "Fade"});
		wi.Add(new CSGOSkins() { prize = 370, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Fade"});
		wi.Add(new CSGOSkins() { prize = 67, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bowie Knife",secondname = "Forest DDPAT"});
		wi.Add(new CSGOSkins() { prize = 78, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Forest DDPAT"});
		wi.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bowie Knife",secondname = "Case Hardened"});
		wi.Add(new CSGOSkins() { prize = 1350, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Case Hardened"});
		wi.Add(new CSGOSkins() { prize = 52, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Bowie Knife",secondname = "Safari Mesh"});
		wi.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Safari Mesh"});
		wi.Add(new CSGOSkins() { prize = 164, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bowie Knife",secondname = "Slaughter"});
		wi.Add(new CSGOSkins() { prize = 302, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Slaughter"});
		wi.Add(new CSGOSkins() { prize = 73, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bowie Knife",secondname = "Stained"});
		wi.Add(new CSGOSkins() { prize = 180, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Stained"});
		wi.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bowie Knife",secondname = "Night"});
		wi.Add(new CSGOSkins() { prize = 123, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bowie Knife",secondname = "Night"});
	}
}
