using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class WOffensiveDatabase : MonoBehaviour {
	public List<CSGOSkins> w = new List<CSGOSkins> ();

	void Start () {
	
		w.Add(new CSGOSkins() { prize = 0.16f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.10f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.27f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.48f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.66f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Galil AR",secondname = "Sandstorm"});
		w.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "Five-Seven",secondname = "Kami"});
		w.Add(new CSGOSkins() { prize = 0.24f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "Five-Seven",secondname = "Kami"});
		w.Add(new CSGOSkins() { prize = 0.32f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "Five-Seven",secondname = "Kami"});
		w.Add(new CSGOSkins() { prize = 0.78f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Kami"});
		w.Add(new CSGOSkins() { prize = 0.72f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Kami"});
		w.Add(new CSGOSkins() { prize = 1.11f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "Five-Seven",secondname = "Kami"});
		w.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Battle-Scared",stattrak = "",firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.13f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.23f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.34f, type = "Blue",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.30f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.22f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.36f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.90f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "M249",secondname = "Magma"});
		w.Add(new CSGOSkins() { prize = 0.15f, type = "Blue",condition ="Well-Worn",stattrak = "",firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 0.09f, type = "Blue",condition ="Field-Tested",stattrak = "", firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 0.12f, type = "Blue",condition ="Minimal Wear",stattrak = "",firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 0.51f, type = "Blue",condition ="Factory New",stattrak = "",firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 0.28f, type = "Blue",condition ="Well-Worn",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 0.25f, type = "Blue",condition ="Field-Tested",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 0.38f, type = "Blue",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 1.48f, type = "Blue",condition ="Factory New",stattrak = "StatTrak", firstname = "PP-Bizon",secondname = "Cobalt Halftone"});
		w.Add(new CSGOSkins() { prize = 1.46f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 0.88f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 0.89f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 1.26f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 3.56f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 2.12f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 2.85f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 4.59f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "FAMAS",secondname = "Pulse"});
		w.Add(new CSGOSkins() { prize = 1.50f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 0.84f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 0.79f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 0.80f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 2.90f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 1.89f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 1.93f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 1.59f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 3.10f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 14.4f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Dual Berettas",secondname = "Marina"});
		w.Add(new CSGOSkins() { prize = 1.03f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "MP9",secondname = "Rose Iron"});
		w.Add(new CSGOSkins() { prize = 1.36f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "MP9",secondname = "Rose Iron"});
		w.Add(new CSGOSkins() { prize = 1.61f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "MP9",secondname = "Rose Iron"});
		w.Add(new CSGOSkins() { prize = 2.49f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "MP9",secondname = "Rose Iron"});
		w.Add(new CSGOSkins() { prize = 3.10f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "MP9",secondname = "Rose Iron"});
		w.Add(new CSGOSkins() { prize = 5.21f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "MP9",secondname = "Rose Iron"});
		w.Add(new CSGOSkins() { prize = 0.83f, type = "Purple",condition ="Battle-Scared",stattrak = "",firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 0.75f, type = "Purple",condition ="Well-Worn",stattrak = "",firstname = "Nova",secondname = "PRising Skull"});
		w.Add(new CSGOSkins() { prize = 0.68f, type = "Purple",condition ="Field-Tested",stattrak = "", firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 0.90f, type = "Purple",condition ="Minimal Wear",stattrak = "",firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 1.11f, type = "Purple",condition ="Factory New",stattrak = "",firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 1.92f, type = "Purple",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 1.99f, type = "Purple",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 1.96f, type = "Purple",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 2.43f, type = "Purple",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 3.49f, type = "Purple",condition ="Factory New",stattrak = "StatTrak", firstname = "Nova",secondname = "Rising Skull"});
		w.Add(new CSGOSkins() { prize = 4.31f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 4.39f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 4.05f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 4.42f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 5.61f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 13.3f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 15.96f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 13.72f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 18.34f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 26.97f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "M4A1-S",secondname = "Guardian"});
		w.Add(new CSGOSkins() { prize = 2.80f, type = "Pink",condition ="Battle-Scared",stattrak = "",firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 2.80f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 2.79f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 3.02f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 6.25f, type = "Pink",condition ="Factory New",stattrak = "",firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 7.29f, type = "Pink",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 8.10f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 8.97f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 12.6f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 42.34f, type = "Pink",condition ="Factory New",stattrak = "StatTrak", firstname = "P250",secondname = "Mehndi"});
		w.Add(new CSGOSkins() { prize = 10.79f, type = "Pink",condition ="Well-Worn",stattrak = "",firstname = "AWP",secondname = "Redline"});
		w.Add(new CSGOSkins() { prize = 7.22f, type = "Pink",condition ="Field-Tested",stattrak = "", firstname = "AWP",secondname = "Redline"});
		w.Add(new CSGOSkins() { prize = 12.06f, type = "Pink",condition ="Minimal Wear",stattrak = "",firstname = "AWP",secondname = "Redline"});
		w.Add(new CSGOSkins() { prize = 32.88f, type = "Pink",condition ="Well-Worn",stattrak = "StatTrak", firstname = "AWP",secondname = "Redline"});
		w.Add(new CSGOSkins() { prize = 22.92f, type = "Pink",condition ="Field-Tested",stattrak = "StatTrak", firstname = "AWP",secondname = "Redline"});
		w.Add(new CSGOSkins() { prize = 41.31f, type = "Pink",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "AWP",secondname = "Redline"});
		w.Add(new CSGOSkins() { prize = 11.46f, type = "Red",condition ="Battle-Scared",stattrak = "",firstname = "M4A4",secondname = "Asiimov"});
		w.Add(new CSGOSkins() { prize = 20.94f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "M4A4",secondname = "Asiimov"});
		w.Add(new CSGOSkins() { prize = 29.82f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "M4A4",secondname = "Asiimov"});
		w.Add(new CSGOSkins() { prize = 33.68f, type = "Red",condition ="Battle-Scared",stattrak = "StatTrak", firstname = "M4A4",secondname = "Asiimov"});
		w.Add(new CSGOSkins() { prize = 89.75f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "M4A4",secondname = "Asiimov"});
		w.Add(new CSGOSkins() { prize = 149.57f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "M4A4",secondname = "Asiimov"});
		w.Add(new CSGOSkins() { prize = 4.73f, type = "Red",condition ="Well-Worn",stattrak = "",firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 2.07f, type = "Red",condition ="Field-Tested",stattrak = "", firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 2.61f, type = "Red",condition ="Minimal Wear",stattrak = "",firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 3.95f, type = "Red",condition ="Factory New",stattrak = "",firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 11.05f, type = "Red",condition ="Well-Worn",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 7.76f, type = "Red",condition ="Field-Tested",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 11.1f, type = "Red",condition ="Minimal Wear",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "The Kraken"});
		w.Add(new CSGOSkins() { prize = 24.91f, type = "Red",condition ="Factory New",stattrak = "StatTrak", firstname = "Sawed-Off",secondname = "The Kraken"});
	
		w.Add(new CSGOSkins() { prize = 107, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		w.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Crimson Web"});
		w.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		w.Add(new CSGOSkins() { prize = 80, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Forest DDPAT"});
		w.Add(new CSGOSkins() { prize = 137, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "M9 Bayonet",secondname = "Slaughter"});
		w.Add(new CSGOSkins() { prize = 240, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "M9 Bayonet",secondname = "Slaughter"});
		w.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Boreal Forest"});
		w.Add(new CSGOSkins() { prize = 100, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Boreal Forest"});
		w.Add(new CSGOSkins() { prize = 188, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Crimson Web"});
		w.Add(new CSGOSkins() { prize = 5000, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Crimson Web"});
		w.Add(new CSGOSkins() { prize = 339, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Karambit",secondname = "Fade"});
		w.Add(new CSGOSkins() { prize = 800, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Karambit",secondname = "Fade"});
		w.Add(new CSGOSkins() { prize = 81, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Safari Mesh"});
		w.Add(new CSGOSkins() { prize = 179, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Karambit",secondname = "Safari Mesh"});
		w.Add(new CSGOSkins() { prize = 88, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Scorched"});
		w.Add(new CSGOSkins() { prize = 148, type = "Rare",condition ="Battle-Scared",stattrak = "StatTrak",firstname = "Karambit",secondname = "Scorched"});
		w.Add(new CSGOSkins() { prize = 333, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Karambit",secondname = "Slaughter"});
		w.Add(new CSGOSkins() { prize = 362, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Slaughter"});
		w.Add(new CSGOSkins() { prize = 122, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Karambit",secondname = "Stained"});
		w.Add(new CSGOSkins() { prize = 206, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Karambit",secondname = "Stained"});
		w.Add(new CSGOSkins() { prize = 91, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Karambit",secondname = "Urban Masked"});
		w.Add(new CSGOSkins() { prize = 127, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Karambit",secondname = "Urban Masked"});
		w.Add(new CSGOSkins() { prize = 37, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Gut Knife",secondname = "Blue Steel"});
		w.Add(new CSGOSkins() { prize = 55, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Blue Steel"});
		w.Add(new CSGOSkins() { prize = 43, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Gut Knife",secondname = "Case Hardened"});
		w.Add(new CSGOSkins() { prize = 74, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Case Hardened"});
		w.Add(new CSGOSkins() { prize = 31, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		w.Add(new CSGOSkins() { prize = 45, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Gut Knife",secondname = "Forest DDPAT"});
		w.Add(new CSGOSkins() { prize = 48, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Flip Knife",secondname = "Blue Steel"});
		w.Add(new CSGOSkins() { prize = 83, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Blue Steel"});
		w.Add(new CSGOSkins() { prize = 168, type = "Rare",condition ="Factory New",stattrak = "",firstname = "Flip Knife",secondname = "Fade"});
		w.Add(new CSGOSkins() { prize = 251, type = "Rare",condition ="Minimal Wear",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Fade"});
		w.Add(new CSGOSkins() { prize = 40, type = "Rare",condition ="Battle-Scared",stattrak = "",firstname = "Flip Knife",secondname = "Stained"});
		w.Add(new CSGOSkins() { prize = 57, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Flip Knife",secondname = "Stained"});
		w.Add(new CSGOSkins() { prize = 82, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Case Hardened"});
		w.Add(new CSGOSkins() { prize = 439, type = "Rare",condition ="Factory New",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Case Hardened"});
		w.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Minimal Wear",stattrak = "",firstname = "Bayonet",secondname = "Scorched"});
		w.Add(new CSGOSkins() { prize = 75, type = "Rare",condition ="Well-Worn",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Scorched"});
		w.Add(new CSGOSkins() { prize = 65, type = "Rare",condition ="Field-Tested",stattrak = "",firstname = "Bayonet",secondname = "Stained"});
		w.Add(new CSGOSkins() { prize = 92, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Stained"});
		w.Add(new CSGOSkins() { prize = 50, type = "Rare",condition ="Well-Worn",stattrak = "",firstname = "Bayonet",secondname = "Urban Masked"});
		w.Add(new CSGOSkins() { prize = 63, type = "Rare",condition ="Field-Tested",stattrak = "StatTrak",firstname = "Bayonet",secondname = "Urban Masked"});

	}
	}
