using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class LOLShopDatabase : MonoBehaviour {
	public List<LOLSkins> shopskins = new List<LOLSkins>();

	void Start () {
		shopskins.Add(new LOLSkins() { prize = 3250, sellprize = 650, name = "Pullsefire Ezreal" });
		shopskins.Add(new LOLSkins() { prize = 3250, sellprize = 650, name = "Spirit Guard Udyr" });
		shopskins.Add(new LOLSkins() { prize = 3250, sellprize = 650, name = "DJ Sona" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Aether Wing Kayle" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Battlecast Alpha Skarner" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Blackfrost Anivia" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Blood Lord Vladimir" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Brolaf" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Corporate Mundo" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Dark Star Thresh" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Demonblade Tryndamere" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Dragon Trainer Tristana" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Dunkmaster Darius" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Gatekeeper Galio" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Gentleman ChoGath" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Infernal Nasus" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Omega Squad Teemo" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Project Ashe" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Project Yi" });
		shopskins.Add(new LOLSkins() { prize = 1820, sellprize = 364, name = "Super Galaxy Rumble" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Ahri" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Corki" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Ezreal" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Hecarim" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Miss Fortune" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Riven" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arcade Sona" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arclight Velkoz" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Arctic Ops Varus" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Ashen Lord Aurelion Sol" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Astronaut Teemo" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "AstroNautilus" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Battlecast KogMaw" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Battlecast Urgot" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Battlecast Velkoz" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Bear Cavalry Sejuani" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Blackthorn Morgana" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Blade Quenn Lissandra" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Cosmic Reaver Kassadin" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Deep Sea Nami" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Dragon Trainer Lulu" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Dragonslayer Pantheon" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "El Macho Mundo" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "El Tigre Braum" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Elderwood Hecarim" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Elderwood LeBlanc" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Eternum Nocturne" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Eternum RekSai" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Firecracker Jinx" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Forsaken Jayce" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Freljord Taliyah" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Full Metal Jayce" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Gravelord Azir" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 195, name = "Guardian of the Sands Xerath" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Headhunter Akali" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Hearthseeker Varus" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "High Noon Jhin" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "iBlitzcrank" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Infernal Diana" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Knockout Lee Sin" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Mad Scientist Ziggs" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Mecha Aatrox" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Mecha Malphite" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Meowkai" });
		shopskins.Add(new LOLSkins() { prize = 975, sellprize = 195, name = "Piltover Customs Heimerdinger" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Fiora" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Graves" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Lulu" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Miss Fortune" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party RekSai" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Taric" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Zac" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Pool Party Ziggs" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Program Lissandra" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Program Soraka" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Ekko" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Fiora" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Katarina" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Leona" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Lucian" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Yasuo" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Project Zed" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Scorched Earth Xerath" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Shadowfire Kindred" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Soul Reaver Draven" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Soulstealer Vladimir" });
		shopskins.Add(new LOLSkins() { prize = 1320, sellprize = 270, name = "Spirit Fire Brand" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Star Guardian Lux" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Steel Legion Garen" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Steel Legion Lux" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Super Galaxy Fizz" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Super Galaxy Shyvana" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Surprise Party Amumu" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Tyrant Swain" });
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Void Bringer Illaoi" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Void Fizz" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Warring Kingdoms Jarvan IV" }); 
		shopskins.Add(new LOLSkins() { prize = 1350, sellprize = 270, name = "Warring Kingdoms Xin Zhao" }); 
	}
}
