using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class ClassicDatabase : MonoBehaviour {
	public List<HSCards> ccards = new List<HSCards> ();

	void Start () {
		#region ccards
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Abomination" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Abusive Sergeant" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Acolyte of Pain" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Alakir the Windlord" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Alarm o Bot" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Aldor Peacekeeper" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Alexstrasza" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Amani Berserker" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ancestral Spirit" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ancient Brewmaster" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ancient Mage" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Ancient of Lore" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Ancient of War" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ancient Watcher" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Angry Chicken" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Arathi Weaponsmith" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Arcane Golem" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Argent Commander" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Argent Protector" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Argent Squire" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Archmage Antonidas" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Armorsmith" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Auchenai Soulpriest" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Avenging Wrath" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Azure Drake" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Bane of Doom" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Baron Geddon" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Battle Rage" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Bestial Wrath" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Betrayal" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Big Game Hunter" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Bite" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Blade Flurry" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Blessed Champion" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Blessing of Wisdom" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Blizzard" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Blood Imp" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Blood Knight" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Bloodmage Thalnos" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Bloodsail Corsair" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bloodsail Raider" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Brawl" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Cabal Shadow Priest" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Cairne Bloodhoof" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Captain Greenskin" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Cenarius" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Circle of Healing" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Coldlight Oracle" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Coldlight Seer" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Commanding Shout" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Conceal" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Cone of Cold" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Counterspell" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Crazed Alchemist" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Cruel Taskmaster" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Cult Master" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Dark Iron Dwarf" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Deadly Shot" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Deathwing" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Defender of Argus" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Defias Ringleader" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Demolisher" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Demonfire" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Dire Wolf Alpha" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Divine Favor" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Doomguard" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Doomhammer" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Doomsayer" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Dread Corsair" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Druid of the Claw" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Dust Devil" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Eaglehorn Bow" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Earth Elemental" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Earth Shock" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Edwin VanCleef" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Emperor Cobra" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Equality" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ethereal Arcanist" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Eviscerate" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Faerie Dragon" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Far Sight" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Felguard" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Fen Creeper" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Feral Spirit" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Flame Imp" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Flare" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Flesheating Ghoul" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Force of Nature" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Forked Lightning" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Freezing Trap" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Frost Elemental" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Force of Nature" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Forked Lightning" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Freezing Trap" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Frost Elemental" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Frothing Berserker" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Gadgetzan Auctioneer" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Gladiators longbow" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Gorehowl" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Grommash Hellscream" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Gruul" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Harrison Jones" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Harvest Golem" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Headcrack" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Hogger" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Holy Fire" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Holy Wrath" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Hungry Crab" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ice Barrier" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Ice Block" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ice Lance" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Illidan Stormrage" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Imp Master" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Injured Blademaster" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Inner Fire" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Inner Rage" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ironbeak Owl" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jungle Panther" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Keeper of the Grove" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Kidnapper" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "King Krush" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "King Mukla" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Kirin Tor Mage" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Knife Juggler" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Lava Burst" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Lay on Hands" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Leeroy Jenkins" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Leper Gnome" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Lightning Bolt" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Lightning Storm" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Lightspawn" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Lightwarden" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Lightwell" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Loot Hoarder" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Lord Jaraxxus" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Lorewalker Cho" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mad Bomber" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Malygos" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mana Addict" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mana Tide Totem" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mana Wraith" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mana Wyrm" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mark of Nature" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mass Dispel" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Master of Disguise" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "MasterSwordsmith" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Millhouse Manastorm" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mind Control Tech" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Mindgames" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mirror Entity" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Misdirection" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mogushan Warden" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 10, type = "Epic", name = "Molten Giant" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mortal Strike" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Mountain Giant" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Murloc Tidecaller" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Murloc Warleader" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Nat Pagle" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Nat Pagle" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Naturalize" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Noble Sacrifice" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Nozdormu" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Onyxia" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Patient Assasin" });	
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Perditions Blade" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Pint Sized Summoner" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Pit Lord" });		
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Power of the wild" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Power Overwhelming" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Preparation" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Priestess of Elune" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Prophet Velen" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "PyroBlast" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Questing Adventurer" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Raging Worgen" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Ragnaros the Firelord" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Rampage" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ravenholdt Assassin" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Redemption" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Repentance" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Savagery" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Savannah Highmane" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Scarlet Crusader" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Scavenging Hyena" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Sea Giant" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Secretkeeper" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Sense Demons" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Shadow Madness" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Shadowflame" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Shadowform" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shadowstep" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Shield Slam" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shieldbearer" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "SI7 Agent" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Silence" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Silver Hand Knight" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Silvermoon Guardian" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Siphon Soul" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Slam" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Snake Trap" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Snipe" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Sorcerers Apprentice" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Soul of the Forest" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Southsea Captain" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Southsea Deckhand" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Spellbender" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Spellbreaker" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Spiteful Smith" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Stampeding Kodo" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Starfall" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Stormforged Axe" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Stranglethorn Tiger" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Summoning Portal" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Sunfury Protector" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Sunwalker" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Sword of Justice" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Sylvanas Windrunner" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Taurer Warrior" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Temple Enforcer" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "The Beast" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "The Black Knight" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Thoughtsteal" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Thrallmar Farseer" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Tinkmaster Overspark" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Tirion Fordring" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Tournament Medic" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Twilight Drake" });
		ccards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Twisting Nether" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Unbound Elemental" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Upgrade" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Vaporize" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Venture Co Mercenary" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Violet Teacher" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Void Terror" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Wild Pyromancer" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Windfury Harpy" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Wisp" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Worgen Infiltrator" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Wrath" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Young Dragonhawk" });
		ccards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Young Priestess" });
		ccards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Youthful Brewmaster" });
		ccards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Ysera" });
		#endregion
	}
	

}
