using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class GTDatabase : MonoBehaviour {
	public List<HSCards> gtcards = new List<HSCards> ();

	void Start () {
	
		#region gtcards
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Acidmaw" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Alexstraszas Champion" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ancestral Knowledge" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Anubarak" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Arcane Blast" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Argent Horserider" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Argent Lance" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Argent Watchman" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Armored Warhorse" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Astral Communion" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Aviana" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ball of Spiders" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bash" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bear Trap" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Beneath the Grounds" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bolster" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bonequard Lieutenant" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Brave Archer" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Buccaneer" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Burgle" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Captured Jormungar" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Coldarra Drake" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Coliseum Manager" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Competitive Spirit" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Confessor Paletress" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Confuse" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Convert" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Crowd Favorite" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Cutpurse" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Dalaran Aspirant" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Dark Bargain" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Darnassus Aspirant" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Demonfuse" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Draenei Totemcarver" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 5, type = "Common", name = "Dragonhawk Rider" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Dreadscale" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Dreadsteed" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Druid of the Saber" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Eadric the Pure" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Effigy" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 400, type = "Epic", name = "Elemental Destruction" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 400, type = "Epic", name = "Enter the Coliseum" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Evil Heckler" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Eydis Darkbane" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Fallen Hero" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Fearsome Doomguard" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Fencing Coach" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Fist of Jaraxxus" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Fjola Lightbane" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Flame Juggler" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Flame Lance" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Flash Heal" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Frigid Snobold" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Frost Giant" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Gadgetzan Jouster" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Garrison Commander" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 1600, type = "Legendary", name = "Gormok the Impaler" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Grand Crusader" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Healing Wave" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Holy Champion" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Charged Hammer" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Chillmaw" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ice Rager" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Icehowl" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Injured Kvaldir" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Justicar Trueheart" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Kings Defender" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kings elekk" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Knight of the Wild" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Kodorider" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kvaldir Raider" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Lance Carrier" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Lights Champion" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Living Roots" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Lowly Squire" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Magnataur Alpha" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Maiden of the Lake" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Master Jouster" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Master of Ceremonies" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mogors Champion" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Muklas Champion" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Mulch" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Murloc Knight" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Mysterious Challenger" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Nexus Champion Saraad" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "North Sea Kraken" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Orgrimmar Aspirant" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Pit Fighter" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Poisoned Blade" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Polymorph Boar" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Power Word Glory" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Powershot" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ram Wrangler" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 20, type = "Epic", name = "Recruiter" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Refreshment Vendor" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Rhonin" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Saboteur" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Savage Combatant" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Sea Reaver" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Seal of Champions" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shado-Pan Rider" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Shadowfiend" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Shady Dealer" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Sideshow Spelleater" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Silent Knight" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Silver Hand Regent" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Sparring Partner" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Spawn of Shadows" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Spellslinger" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Stablemaster" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "The Mistcaller" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "The Skeleton Knight" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Thunder Bluff Valiant" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Tiny Knight of Evil" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Totem Golem" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Tournament Attendee" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Tuskarr Jouster" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Tuskarr Totemic" });
		gtcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Twilight Guardian" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Undercity Valiant" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Varian Wrynn" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Void Crusher" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Warhorse Trainer" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Wildwalker" });
		gtcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Wilfred Fizzlebang" });
		gtcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Wrathguard" });
		gtcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Wyrmrest Agent" });
		#endregion
	}

}
