using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class MSGDatabase : MonoBehaviour {
	public List<HSCards> msgcards = new List<HSCards>();

	void Start () {
		#region msgcards
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Abyssal Enforcer"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Alley Armorsmith"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Alleycat"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ancient of Blossoms"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Auctionmaster Beardo"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Aya Blackpaw"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Backroom Bouncer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Backstreet Leper"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Big Time Racketeer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Blastcrystal Potion"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Bloodfury Potion"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Blowgill Sniper"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Blubber Baron"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Bomb Squad"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Brass Knuckles"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Burgly Bully"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Call in the Finishers"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Celestial Dreamer"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Counterfeit Coin"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Cryomancer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Crystalweaver"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Daring Reporter"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Defias Cleaner"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Devolve"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Dirty Rat"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Dispatch Kodo"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Don HanCho"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Doppelgangster"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Dragonfire Potion"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Drakonid Operative"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Fel Orc Soulfiend"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Felfire Potion"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Fight Promoter"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Finders Keepers"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Finja, the Flying Star"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Freezing Potion"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Friendly Bartender"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Gadgetzan Ferryman"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Gadgetzan Socialite"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Genzo, the Shark"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Getaway Kodo"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Greater Arcane Missiles"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Greater Healing Potion"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Grimestreet Enforcer"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Grimestreet Informant"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Grimestreet Outfitter"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Grimestreet Pawnbroker"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Grimestreet Protector"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Grimestreet Smuggler"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Grimscale Chum"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Grimy Gadgeteer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Grook Fu Master"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Hidden Cache"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Hired Gun"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Hobart Grapplehammer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Hozen Healer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "I Know a Guy"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Inkmaster Solia"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Behemoth"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Blossom"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Chieftain"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Jade Claws"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Jade Idol"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Lightning"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Shuriken"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Spirit"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Jade Swarmer"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Jinyu Waterspeaker"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kabal Chemist"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Kabal Courier"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Kabal Crystal Runner"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kabal Lackey"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kabal Songstealer"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kabal Talonpriest"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Kabal Trafficker"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Kazakus"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Knuckles"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Kooky Chemist"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Krul the Unshackled"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Kun the Forgotten King"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Leatherclad Hogleader"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Lotus Agents"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Lotus Assassin"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Lotus Illusionist"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Luckydo Buccaneer"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Lunar Visions"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Madam Goya"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Mana Geode"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Manic Soulcaster"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mark of the Lotus"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Mayor Noggenfogger"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Meanstreet Marshal"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Mistress of Mixtures"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Naga Corsair"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Patches the Pirate"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Pilfered Power"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Pint-Size Potion"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Piranha Launcher"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Potion of Madness"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Potion of Polymorph"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Public Defender"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Rat Pack"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Raza the Chained"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Red Mana Wyrm"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Seadvil Stinger"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Second-Rate Bruiser"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Sergeant Sally"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shadow Rager"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Shadow Sensei"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Shaku, the Collector"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shaky Zipgunner"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Sleep with the Fishes"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Small-Time Buccaneer"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Small-Time Recruits"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Smugglers Crate"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Smugglers Run"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Spiked Hogrider"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Stolen Goods"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Street Trickster"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Streetwise Investigator"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Tanaris Hogchopper"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Toxic Sewer Ooze"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Trogg Beastrager"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Unlicensed Apothecary"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Virmen Sensei"});
		msgcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Volcanic Potion"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Weasel Tunneler"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "White Eyes"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Wickerflame Burnbristle"});
		msgcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Wind-ip Burglebot"});
		msgcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Worgen Greaser"});
		msgcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Wrathion"});
		#endregion

	
	}
	}
