using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class WDatabase : MonoBehaviour {
	public List<HSCards> wcards = new List<HSCards> ();

	void Start () {
		#region wcards
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "A Light in the Darkness"});
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Aberrant Berserker" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Addled Grizzly" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Amgam Rager" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Ancient Harbinger" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Ancient Shieldbearer" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Anomalus" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Beckoner of Evil" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bilefin Tidehunter" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Blackwater Pirate" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Blade of CThun" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bladed Cultist" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Blood of the Ancient One" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Blood to Ichor" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Blood Warriors" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bloodhoof Brave" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Bloodsail Cultist" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Bog Creeper" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Cabalists Tome" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "call of the wild" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 100, type = "Common", name = "Carrion Grub" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Corrupted Healbot" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Corrupted Seer" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Crazed Worshipper" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "CThuns Chosen" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Cult Apothecary" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Cult Sorcerer" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Cyclopian Horror" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Dark Arakkoa" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Darkshire Alchemist" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Darkshire Councilman" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Darkshire Librarian" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Darkspeaker" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Deathwing, Dragonlord" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Demented Frostcaller" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Disciple of CThun" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Divine Strength" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "DOOM!" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Doomcaller" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Duskboar" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Eater of Secrets" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Eldritch Horror" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Embrace the Shadow" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Eternal Sentinel" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Evolve" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Evolved Kobold" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Faceless Behemoth" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Faceless Shambler" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Faceless Summoner" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Fandral Staghelm" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Feral Rage" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Fiery Bat" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Flamewreathed Faceless" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Forbidden Ancien" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Forbidden Flame" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Forbidden Healing" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Forbidden Ritual" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Forbidden Shaping" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Forlon Stalker" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Giant Sand Worm" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Grotesque Dragonhawk" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Hallazeal the Ascended" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Hammer of Twilight" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Herald Volazj" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Hogger, Doom of Elwynn" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Hooded Acolyte" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Cho gall" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "infest" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Infested Tauren" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Infested Wolf" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Journey Below" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Klaxxi Amber-Weaver" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Lock and Load" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Malkorok" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "mark of yshaarj" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Master of Evolution" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Midnight Drake" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Mire Keeper" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Mukla,  Tyrant of the Vale" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Nat, the Darkfisher" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Nerubian Prophet" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "NZoth, the Corruptor" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Nzoths First Mate" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "On the Hunt" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Polluted Hoarder" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Power Word- Tentacles" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Primal Fusion" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Princess Huhuran" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Psych-o-Tron" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Ragnaros, Lightlord" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Rallying Blade" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Ravaging Ghoul" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Renounce Darkness" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Scaled Nightmare" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Selfless Hero" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Servant of Yogg-Saron" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shadow Strike" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Shadow Word- Horror" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Shadowcaster" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Shatter" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Shifter Zerus" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Shifting Shade" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Silithid Swarmer" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Skeram Cultist" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Soggoth the Slitherer" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Southsea Squidface" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Spawn of NZoth" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Spreading Madness" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Squirming Tentacle" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Stand Against Darkness" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Steward of Darkshire" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Stormcrack" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Tentacle of NZoth" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Tentacles for Arms" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "The Boogeymonster" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Thing from Below" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Thistle Tea" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Twilight Darkmender" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Twilight Elder" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Twilight Flamecaller" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Twilight Geomancer" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Twilight Summoner" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Twin Emperor Veklor" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Twisted Worgen" });
		wcards.Add(new HSCards() { prize = 100, sellprize = 20, type = "Rare", name = "Undercity Huckster" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Usher of Souls" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Validated Doomsayer" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Vilefin Inquisitor" });
		wcards.Add(new HSCards() { prize = 400, sellprize = 100, type = "Epic", name = "Whisps of the Old Gods" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Xaril, Poisoned Mind" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Y Shaarj, Rage Unbound" });
		wcards.Add(new HSCards() { prize = 1600, sellprize = 400, type = "Legendary", name = "Yogg-Saron, Hopes End" });
		wcards.Add(new HSCards() { prize = 40, sellprize = 5, type = "Common", name = "Zealous Initiate" });
		#endregion


	
	}
	

}
